const BASE_EXACT_ENGLISH: Record<string, string> = {
  'Sistema online': 'System online',
  'Sistema Online': 'System Online',
  'Bem-vindo ao Sistema': 'Welcome to the System',
  'Primeiro despertar': 'First Awakening',
  'Registre sua identidade e desbloqueie o protocolo de evolução.': 'Register your identity and unlock the evolution protocol.',
  'Acesse sua jornada de evolução, quests, bosses e progressão diária.': 'Access your journey of evolution, quests, bosses, and daily progression.',
  'Codinome': 'Codename',
  'Identidade': 'Identity',
  'Chave de acesso': 'Access key',
  'Confirmar chave': 'Confirm key',
  'Recuperar chave': 'Recover key',
  'Ocultar senha': 'Hide password',
  'Mostrar senha': 'Show password',
  'Ocultar confirmacao': 'Hide confirmation',
  'Mostrar confirmacao': 'Show confirmation',
  'Sincronizando...': 'Synchronizing...',
  'Despertar no Sistema': 'Awaken in the System',
  'Iniciar Ascensao': 'Begin Ascension',
  'Ja possui registro no sistema?': 'Already registered in the System?',
  'Primeira vez no sistema?': 'First time in the System?',
  'Acessar conta': 'Access account',
  'Solicitar despertar': 'Request awakening',
  'Gate calibrado': 'Gate calibrated',
  'Status preview': 'Status preview',
  'Classe': 'Class',
  'Boss da Semana': 'Weekly Boss',
  'Quests da comunidade': 'Community quests',
  'Mensagem do sistema': 'System message',
  'Transforme rotina em progressao visivel.': 'Turn routine into visible progression.',
  'Cada treino, refeicao e decisao vira XP para a sua proxima versao.': 'Every workout, meal, and decision becomes XP for your next version.',
  'Protocolo ativo': 'Active protocol',
  'XP para Level 13': 'XP to Level 13',
  'As senhas não coincidem': 'Passwords do not match',
  'Acesso restrito — Nível insuficiente.': 'Restricted access — Insufficient level.',

  'Calibração Biológica': 'Biological Calibration',
  'Protocolo de Identificação': 'Identification Protocol',
  'O Sistema precisa reconhecer o Caçador.': 'The System must recognize the Hunter.',
  'Sua assinatura inicial será gravada antes da abertura da primeira Fenda.': 'Your initial signature will be recorded before the first Gate opens.',
  'Nome do Caçador': 'Hunter Name',
  'Seu nome verdadeiro...': 'Your real name...',
  'Data de Nascimento': 'Date of Birth',
  'Sexo': 'Sex',
  'Masculino': 'Male',
  'Feminino': 'Female',
  'PRÓXIMO PASSO': 'NEXT STEP',
  'Análise Corporal': 'Body Analysis',
  'Varredura Biométrica': 'Biometric Scan',
  'O Sistema está lendo sua base física.': 'The System is reading your physical baseline.',
  'Cada métrica ajusta a dificuldade das primeiras missões.': 'Each metric adjusts the difficulty of your first missions.',
  'Altura (cm)': 'Height (cm)',
  'Peso Atual (kg)': 'Current Weight (kg)',
  'Peso Meta (kg)': 'Target Weight (kg)',
  'Objetivo Nutricional': 'Nutrition Goal',
  'Perder peso': 'Lose weight',
  'Manter peso': 'Maintain weight',
  'Ganhar peso': 'Gain weight',
  'Foco de Treino': 'Training Focus',
  'Musculação': 'Strength Training',
  'Funcional': 'Functional Training',
  'Esportes de Combate': 'Combat Sports',
  'Calistenia': 'Calisthenics',
  'Flexibilidade / Yoga': 'Flexibility / Yoga',
  'Missão Central': 'Core Mission',
  'O Sistema detectou múltiplos caminhos. Qual representa sua essência?': 'The System detected multiple paths. Which one represents your essence?',
  'Esta escolha define o primeiro eixo das suas quests de evolução.': 'This choice defines the first axis of your evolution quests.',
  'Evolução Geral': 'Overall Growth',
  'Quero crescer em todas as áreas da vida.': 'I want to grow in every area of life.',
  'Performance & Saúde': 'Performance & Health',
  'Foco em físico, energia e saúde duradoura.': 'Focus on fitness, energy, and lasting health.',
  'Independência Financeira': 'Financial Independence',
  'Construir riqueza e liberdade financeira real.': 'Build wealth and real financial freedom.',
  'Carreira & Habilidades': 'Career & Skills',
  'Dominar minha área e avançar na carreira.': 'Master my field and advance my career.',
  'Calibração de Rank': 'Rank Calibration',
  'Informe seu Rank inicial para calibrar a ameaça.': 'Enter your initial Rank to calibrate the threat.',
  'O Sistema ajustará as primeiras missões sem quebrar seu ritmo.': 'The System will adjust your first missions without disrupting your pace.',
  'Iniciante': 'Beginner',
  'Começando agora. Cada passo conta.': 'Starting now. Every step counts.',
  'Intermediário': 'Intermediate',
  'Tenho consistência. Quero ir além.': 'I am consistent. I want to go further.',
  'Avançado': 'Advanced',
  'Alta performance. Busco o limite máximo.': 'High performance. I seek the highest limit.',
  'AVANÇAR': 'CONTINUE',
  'Transmissão Recebida': 'Transmission Received',
  'Eu sou o Arquiteto.': 'I am the Architect.',
  'Fui eu quem construiu o sistema das Fendas. Fui eu quem deu a caçadores como Sung Jin-Woo uma segunda chance.': 'I built the Gate System. I gave hunters like Sung Jin-Woo a second chance.',
  'Agora, eu te ofereço a mesma oportunidade.': 'Now I offer you the same opportunity.',
  'Mas para calibrar seu poder, preciso entender do que você é feito.': 'But to calibrate your power, I need to understand what you are made of.',
  '"Responda com honestidade. O sistema não mente — e você também não deveria."': '"Answer honestly. The System does not lie—and neither should you."',
  'ACEITAR O DESAFIO': 'ACCEPT THE CHALLENGE',
  'Avaliação do Sistema': 'System Assessment',
  'Avaliação do Arquiteto': 'Architect Assessment',
  'REVELAR MEU CAMINHO': 'REVEAL MY PATH',
  'PRÓXIMA QUESTÃO': 'NEXT QUESTION',
  'Sistema de Avaliação · Solo Leveling': 'Assessment System · Solo Leveling',
  'Analisando Caçador...': 'Analyzing Hunter...',
  '"O sistema não escolhe os fracos. Ele revela os escolhidos."': '"The System does not choose the weak. It reveals the chosen."',
  'Resultado da Avaliação · Sistema do Arquiteto': 'Assessment Result · Architect System',
  'Classe despertada:': 'Awakened class:',
  'O Sistema identificou sua essência. Confirme o despertar ou escolha outro caminho antes de entrar na Fenda.': 'The System identified your essence. Confirm the awakening or choose another path before entering the Gate.',
  '"A fraqueza não é uma limitação. É um ponto de partida." — Arquiteto, Solo Leveling': '"Weakness is not a limitation. It is a starting point." — Architect, Solo Leveling',
  'Desbloqueado': 'Unlocked',
  'Conquista de despertar': 'Awakening achievement',
  'Atributos iniciais': 'Initial attributes',
  'Sua classe acabou de despertar.': 'Your class has just awakened.',
  'Recomendado': 'Recommended',
  'Em breve': 'Coming soon',
  'DESPERTAR PODER': 'AWAKEN POWER',
  'Evolução de Classe': 'Class Evolution',
  'Selecione o Nível de Rank': 'Select Rank Level',
  'Atributo & Potencial de Mana': 'Attribute & Mana Potential',
  'Use o seletor para vislumbrar seu poder futuro no Rank S.': 'Use the selector to glimpse your future power at Rank S.',

  'Perfil do Caçador': 'Hunter Profile',
  'Ver avatar': 'View avatar',
  'Sem classe': 'No class',
  'Título:': 'Title:',
  'Experiência do Hunter': 'Hunter Experience',
  'Próximo Rank': 'Next Rank',
  'Resumo de Hoje': 'Today Summary',
  'XP ganhos': 'XP earned',
  'Status de Hoje': 'Today Status',
  'XP acumulado hoje': 'XP earned today',
  'XP bônus não consome o limite diário': 'Bonus XP does not consume the daily limit',
  'Missões Diárias': 'Daily Quests',
  'Gerenciar Hábitos': 'Manage Habits',
  'Códex de Atividades': 'Activity Codex',
  'Nova Missão': 'New Quest',
  'Novo Hábito': 'New Habit',
  'Salvar': 'Save',
  'Cancelar': 'Cancel',
  'Excluir': 'Delete',
  'Editar': 'Edit',
  'Concluir': 'Complete',
  'Adicionar': 'Add',
  'Fechar': 'Close',
  'Voltar': 'Back',
  'Continuar': 'Continue',
  'Confirmar': 'Confirm',
  'Carregando...': 'Loading...',
  'Nenhum registro encontrado.': 'No records found.',
  'Hoje': 'Today',
  'Ontem': 'Yesterday',
  'Ativo': 'Active',
  'Inativo': 'Inactive',
  'Todos': 'All',
  'Buscar': 'Search',
  'Recompensa': 'Reward',
  'Progresso': 'Progress',
  'Meta': 'Goal',
  'Metas': 'Goals',
  'Treinos': 'Workouts',
  'Exercícios': 'Exercises',
  'Rotinas': 'Routines',
  'Evolução': 'Progression',
  'Histórico': 'History',
  'Recuperação': 'Recovery',
  'Alimentação': 'Nutrition',
  'Finanças': 'Finances',
  'Sono': 'Sleep',
  'Meditação': 'Meditation',
  'Lazer': 'Leisure',
  'Força': 'Strength',
  'Inteligência': 'Intelligence',
  'Resistência': 'Endurance',
  'Vitalidade': 'Vitality',
  'Disciplina': 'Discipline',
  'Sabedoria': 'Wisdom',
  'Equilíbrio': 'Balance',
  'Força Vital': 'Vital Force',
  'Ritmo de Evolução': 'Evolution Pace',
  'Ritmo elevado. Sua progressão diária está consistente.': 'High pace. Your daily progression is consistent.',
  'Potencial disponível. Complete novas ações para fortalecer sua ficha.': 'Potential available. Complete new actions to strengthen your profile.',
  'Quest diária recomendada': 'Recommended daily quest',
  'Missão física prioritária': 'Priority physical mission',
  'Próxima quest em preparação': 'Next quest being prepared',
  'Todas as missões de hoje foram concluídas.': 'All of today’s quests are complete.',
  'Abrir missões': 'Open quests',
  'Iniciar missão': 'Start quest',
  'Ver missão': 'View quest',
  'Aguardando evolução': 'Awaiting progression',
  'Progresso diário': 'Daily progress',
  'Protocolo de recuperação': 'Recovery protocol',
  'Treino concluído': 'Workout completed',
  'Refeição registrada': 'Meal recorded',
  'Finanças atualizadas': 'Finances updated',
  'Sequência mantida': 'Streak maintained',
  'Sem variação hoje': 'No change today',
  'Não definida': 'Not defined',
  'Máximo': 'Maximum',
  'Parâmetros do Sistema': 'System Parameters',
  'Complete uma missão para gerar seu primeiro registro.': 'Complete a quest to generate your first record.',
  'Avatar ampliado do Caçador': 'Enlarged Hunter avatar',

  'Códex do Caçador': 'Hunter Codex',
  'Ciclo diário concluído': 'Daily cycle complete',
  'Sistema sincronizado. Todas as quests do ciclo foram concluídas.': 'System synchronized. Every quest in this cycle is complete.',
  'Automática': 'Automatic',
  'diretriz disponível': 'directive available',
  'diretrizes disponíveis': 'directives available',
  'Concluída': 'Completed',
  'EM EXECUÇÃO': 'IN PROGRESS',
  'MISSÃO CONCLUÍDA': 'QUEST COMPLETED',
  'ANOMALIA CONCLUÍDA': 'ANOMALY COMPLETED',
  'TREINO CONCLUÍDO': 'WORKOUT COMPLETED',
  'REFEIÇÃO FEITA': 'MEAL COMPLETED',
  'Abrir módulo': 'Open module',
  'Deletar missão permanente': 'Permanently delete quest',
  'Registrar Operações Financeiras do Dia': 'Log Today’s Financial Operations',
  'Refeições Saudáveis': 'Healthy Meals',
  'Treino de Força': 'Strength Training',
  'Trabalhar (Foco Diário)': 'Work (Daily Focus)',
  'Trabalhar (Foco Máximo)': 'Work (Maximum Focus)',
  'Programação & Tech': 'Programming & Tech',
  'Tocar Instrumento / Música': 'Play Instrument / Music',
  'ALIMENTAÇÃO': 'NUTRITION',
  'FINANÇAS': 'FINANCES',
  'FORÇA': 'STRENGTH',
  'INTELIGÊNCIA': 'INTELLIGENCE',
  'RESISTÊNCIA': 'ENDURANCE',
  'Força (FOR)': 'Strength (STR)',
  'Inteligência (INT)': 'Intelligence (INT)',
  'Resistência (RES)': 'Endurance (END)',
  'Saúde': 'Health',
  'Sem horário': 'No scheduled time',
  'Falha na conexão neural com o Groq.': 'Neural connection to Groq failed.',
  'Apoia energia, recuperação e consistência nutricional.': 'Supports energy, recovery, and nutritional consistency.',
  'Eleva a capacidade física e consolida progressão de cargas.': 'Raises physical capacity and consolidates load progression.',
  'Aprimora condicionamento e capacidade de sustentar esforço.': 'Improves conditioning and sustained effort capacity.',
  'Fortalece constância profissional e execução sob pressão.': 'Strengthens professional consistency and execution under pressure.',
  'Amplia autonomia, entrega e resiliência profissional.': 'Expands autonomy, delivery, and professional resilience.',
  'Expande repertório, memória e adaptação cognitiva.': 'Expands repertoire, memory, and cognitive adaptability.',
  'Fortalece raciocínio sistêmico e solução de problemas.': 'Strengthens systems thinking and problem-solving.',
  'Promove expressão criativa e equilíbrio mental.': 'Promotes creative expression and mental balance.',
  'Reforça manutenção, autocuidado e progresso sustentável.': 'Reinforces maintenance, self-care, and sustainable progress.',

  'Biblioteca de exercícios': 'Exercise Library',
  'Buscar exercício ou grupo muscular...': 'Search exercise or muscle group...',
  'Novo Exercício': 'New Exercise',
  'Definir exercício': 'Set exercise',
  'Nome do Exercício *': 'Exercise Name *',
  'Este exercício já faz parte da rotina selecionada.': 'This exercise is already part of the selected routine.',
  'Não foi possível adicionar o exercício à rotina.': 'Could not add the exercise to the routine.',
  'Deseja mesmo abandonar o treino atual? Seu progresso nesta sessão será perdido.': 'Do you really want to abandon the current workout? This session’s progress will be lost.',
  'Rotina excluída com sucesso': 'Routine deleted successfully',
  'Evolução física estruturada': 'Structured physical progression',
  'Missão de hoje': 'Today’s mission',
  'Missão física atual': 'Current physical mission',
  'Base muscular e consistência': 'Muscular foundation and consistency',
  'Hipertrofia com recuperação': 'Hypertrophy with recovery',
  'Volume e frequência máxima': 'Maximum volume and frequency',
  'Especialização muscular': 'Muscle specialization',
  'Massa magra e gasto energético': 'Lean mass and energy expenditure',
  'Progressão de força': 'Strength progression',
  'Potência': 'Power',
  'Glúteos': 'Glutes',
  'Tríceps': 'Triceps',
  'Bíceps': 'Biceps',
  'Máquina': 'Machine',

  'Café da Manhã': 'Breakfast',
  'Almoço': 'Lunch',
  'Café da Tarde': 'Afternoon Snack',
  'Café proteico': 'Protein Coffee',
  'Lanche rápido': 'Quick Snack',
  'Nome da refeição': 'Meal name',
  'Registrar no diário': 'Log in diary',
  'Confirmar Recuperação': 'Confirm Recovery',
  'Concluir edição': 'Finish editing',
  'Descreva a refeição para que o Códex possa calibrar.': 'Describe the meal so the Codex can calibrate it.',
  'Registre uma refeição para iniciar sua recuperação de mana.': 'Log a meal to begin your mana recovery.',
  'Não foi possível registrar a refeição. Tente novamente.': 'The meal could not be logged. Try again.',
  'Não foi possível concluir a refeição.': 'The meal could not be completed.',
  'Houve uma anomalia na calibração neural. Tente novamente.': 'There was an anomaly in neural calibration. Try again.',
  'A referência diária foi ultrapassada. Siga normalmente e priorize consistência ao longo dos dias.': 'The daily reference was exceeded. Continue normally and prioritize consistency over time.',
  'Energia diária': 'Daily energy',
  'Meta indisponível': 'Goal unavailable',
  'Alimento indisponível': 'Food unavailable',
  'Disponível': 'Available',
  'Proteína': 'Protein',
  'Proteínas': 'Protein',
  'Porção (ex: 2)': 'Serving (e.g. 2)',
  'Kcal por porção/100g': 'Kcal per serving/100g',

  'Registrar Transação': 'Log Transaction',
  'Descrição': 'Description',
  'Despesa (Saída)': 'Expense (Outflow)',
  'Título do Objetivo': 'Goal Title',
  'Meta Única (Ex: Comprar Carro)': 'One-Time Goal (e.g. Buy a Car)',
  'Objetivo Único': 'One-Time Goal',
  'Reserva de Emergência': 'Emergency Fund',
  'Salário': 'Salary',
  'Ações': 'Actions',
  'Excluir transação': 'Delete transaction',
  'Por favor, preencha a descrição e um valor maior que zero.': 'Please enter a description and an amount greater than zero.',
  'Por favor, insira o título e o valor alvo da meta.': 'Please enter the goal title and target amount.',
  'Erro ao registrar transação no Supabase.': 'Error logging transaction in Supabase.',
  'Erro ao excluir a transação.': 'Error deleting transaction.',

  'Estado de equilíbrio': 'Balance state',
  'Equilíbrio restaurado': 'Balance restored',
  'Mana em recuperação': 'Mana recovering',
  'Recuperação em progresso': 'Recovery in progress',
  'Meta alcançada': 'Goal reached',
  'Desconexão completa': 'Complete disconnection',
  'Hobby & Desconexão': 'Hobby & Disconnection',
  'Meditação / Calma': 'Meditation / Calm',
  'Meditação acumulada': 'Accumulated meditation',
  'Sem observações': 'No notes',
  'Ex: Leitura, Violão, Caminhada...': 'E.g. Reading, Guitar, Walking...',
  'respiração, meditação e foco': 'breathing, meditation, and focus',

  'Nome do hábito *': 'Habit name *',
  'Título da quest *': 'Quest title *',
  'Horário (Opcional)': 'Time (Optional)',
  'Criar Hábito': 'Create Habit',
  'Ex: Estudo, Treino, Saúde, Mindset...': 'E.g. Study, Workout, Health, Mindset...',
  'Ex: Estudo, Treino, Hábito...': 'E.g. Study, Workout, Habit...',
  'Exercício Desconhecido': 'Unknown Exercise',
  'Alto em proteína': 'High protein',
  'Energia e reposição': 'Energy and replenishment',
  'Equilíbrio e consistência': 'Balance and consistency',
  'Expandir cardápio': 'Expand meal plan',
  'Recolher cardápio': 'Collapse meal plan',
  'Pós-treino': 'Post-workout',
  'Pré-treino': 'Pre-workout',
  'Suporte à força e recuperação': 'Strength and recovery support',
  'Rápido': 'Quick',
  'Fácil': 'Easy',
  'Nenhum': 'None',
  'Nenhuma': 'None',
  'Nenhum registro': 'No records',
  'Buscar...': 'Search...',
  'Criar Quest': 'Create Quest',
  'Criando...': 'Creating...',
  'Novo': 'New',
  'Nova': 'New',
  'Novo valor': 'New amount',
  'Módulo Físico': 'Physical Module',
  'Módulo Fortuna': 'Fortune Module',
  'Boss disponível': 'Boss available',
  'Classe não definida': 'Class not selected',
  'Estudar Novo Idioma': 'Study a New Language',
  'Buscar suprimentos nutricionais...': 'Search nutritional supplies...',
  'Multiplicador ativo': 'Active multiplier',
  'Disponível amanhã': 'Available tomorrow',
  '1 uso disponível': '1 use available',
  'O dano principal é aplicado automaticamente ao concluir atividades nos módulos do Ascend.': 'Main damage is applied automatically when activities are completed in Ascend modules.',
  'Golpe crítico · multiplicador ativo': 'Critical strike · active multiplier',
  'Acesso restrito — Faça login para entrar na fenda.': 'Restricted access — Sign in to enter the Gate.',
  'Falha ao sincronizar a fenda': 'Failed to synchronize the Gate',
  'Erro ao sincronizar com o banco.': 'Failed to synchronize with the database.',
  'Formato de dados incompleto retornado pelo modelo de IA.': 'The AI model returned incomplete data.',
  'Falha ao registrar sono.': 'Failed to log sleep.',
  'Falha ao registrar lazer.': 'Failed to log leisure.',
  'A sincronização do Codex expirou. O banco de dados pode estar lento ou inacessível.': 'Codex synchronization timed out. The database may be slow or unavailable.',
  'A conexão de telemetria expirou. O banco de dados pode estar lento ou inacessível.': 'Telemetry connection timed out. The database may be slow or unavailable.',
  'Nenhuma credencial nova foi informada.': 'No new credentials were provided.',
  'Dados de Identidade Opcionais no Codex': 'Optional Identity Data in the Codex',
  'Nova Senha': 'New Password',
  'Ação totalmente irreversível!': 'This action is completely irreversible!',
  'Purificar Atributos?': 'Purify Attributes?',
  'Senha': 'Password',
  'Sua senha': 'Your password',
  'Entrar': 'Sign in',
  'Já despertou?': 'Already awakened?',
  'Novo Hunter?': 'New Hunter?',
  'Senha mínima: 6 caracteres.': 'Minimum password length: 6 characters.',
  'Um novo despertar foi detectado.': 'A new awakening has been detected.',
  'Criar é Evoluir': 'To Create Is to Evolve',
  'Classe determinada pelo Arquiteto.': 'Class determined by the Architect.',
  'Despertar da Classe': 'Class Awakening',
  'Acessar módulo': 'Open module',
  'Energia': 'Energy',
  'Energia (kcal)': 'Energy (kcal)',
  'Dificuldade': 'Difficulty',
  'Preparo': 'Preparation',
  'Cor personalizada': 'Custom color',
  'FICHA DE INTEGRAÇÃO': 'NEURAL INTEGRATION',
  'Canalizando Energia...': 'Channeling Energy...',
  'Descrição do Boss': 'Boss Description',
  'Regeneração': 'Regeneration',
  'Desfazer atividades restaura o mesmo dano aplicado, impedindo farm de golpes.': 'Undoing activities restores the same damage dealt, preventing attack farming.',
  'Nenhuma raid ativa encontrada na fenda.': 'No active raid found in the Gate.',
  'Eventos recentes registrados durante esta sessão de raid.': 'Recent events recorded during this raid session.',
  'Regeneração de HP': 'HP Regeneration',
  'Registro de todos os chefes derrotados no servidor do ASCEND': 'Record of every boss defeated on the ASCEND server',
  'Registrando no Codex...': 'Recording in the Codex...',
  'Ex: Guardar 40 mil para o carro': 'E.g. Save 40,000 for a car',
  'Nenhuma resposta retornada do modelo de IA.': 'The AI model returned no response.',
  'Complete no perfil:': 'Complete in profile:',
  'Criar quest': 'Create quest',
  'Faltam no perfil:': 'Missing from profile:',
  'Acelera a regeneração celular e a imunidade biológica.': 'Accelerates cellular regeneration and biological immunity.',
  'Eleva o dano físico bruto e a densidade miofibrilar.': 'Raises raw physical damage and myofibrillar density.',
  'Otimiza o fluxo de oxigênio e a capacidade cardiovascular.': 'Optimizes oxygen flow and cardiovascular capacity.',
  'Fortalece a constância profissional e a entrega sob pressão.': 'Strengthens professional consistency and delivery under pressure.',
  'Esforço adicional que eleva sua autonomia financeira e resiliência.': 'Additional effort that increases financial autonomy and resilience.',
  'O Corpo é a Arma': 'The Body Is the Weapon',
  'A Mente é o Campo de Batalha': 'The Mind Is the Battlefield',
  'O Equilíbrio é Poder': 'Balance Is Power',
  'Calibração de Identidade': 'Identity Calibration',
  'A fraqueza não é uma limitação. É um ponto de partida.': 'Weakness is not a limitation. It is a starting point.',
  'Nome de Batismo (Codinome Real)': 'Given Name (Real Codename)',
  'Títulos liberados ao conquistar marcos importantes. Escolha um para exibir no seu perfil.': 'Titles unlocked by reaching major milestones. Choose one to display on your profile.',
  'Modificação de Chaves Criptográficas': 'Cryptographic Key Modification',
  'Calibração de Interface e Guias Virtuais': 'Interface Calibration and Virtual Guides',
  'Conexão Supabase': 'Supabase Connection',
  'Anomalia de Conexão Detectada': 'Connection Anomaly Detected',
  'Registros na Nuvem (Sincronização)': 'Cloud Records (Synchronization)',
  'Sincronização Forçada': 'Forced Synchronization',
  'Ações Irreversíveis de Modificação de Matriz': 'Irreversible Matrix Modification Actions',
  'Destruição da Matriz!': 'Matrix Destruction!',
  'VALIDAÇÃO FALHOU: As senhas digitadas não coincidem.': 'VALIDATION FAILED: The passwords do not match.',
  'REGISTRO ATUALIZADO: Sua identidade no Codex foi gravada com sucesso.': 'RECORD UPDATED: Your identity was successfully recorded in the Codex.',
  '+ XP hoje': '+ XP today',
  '+ hoje': '+ today',
  'Hunter em uma fenda de energia do Ascend System': 'Hunter inside an Ascend System energy Gate',
  'Transforme rotina em progressão visível.': 'Turn routine into visible progression.',
  'ERRO DE GRAVAÇÃO:': 'WRITE ERROR:',
  'ERRO DE SEGURANÇA:': 'SECURITY ERROR:',
  'ERRO DE REDEFINIÇÃO:': 'RESET ERROR:',
  'ERRO DE RESET COMPLETO:': 'FULL RESET ERROR:',
  'Classe atual': 'Current class',
  'Módulo': 'Module',
  'Categoria': 'Category',
  'Taxa de Aporte Saudável:': 'Healthy Contribution Rate:',
  'Conversão de energia': 'Energy conversion',
  'Nome do item': 'Item name',
  'Ir para Módulo': 'Go to Module',
  'Nome da Rotina': 'Routine Name',
  'Esta ação é irreversível e removerá todos os dados vinculados.': 'This action is irreversible and will remove all linked data.',
  'Esqueceu a senha?': 'Forgot your password?',
  'Volume Total': 'Total Volume',
  'Janela de Status': 'Status Window',
  'Atributos Principais': 'Primary Attributes',
  'Leitura Holográfica': 'Holographic Reading',
  'Dimensões da Vida': 'Life Dimensions',
  'Domínios de Evolução': 'Evolution Domains',
  'Leitura Diária': 'Daily Reading',
  'Recursos do Dia': 'Daily Resources',
  'Perfil dominante': 'Dominant Profile',
  'Foco recomendado': 'Recommended Focus',
  'Último registro': 'Last Record',
  'Próximo marco': 'Next Milestone',
  'XP restantes': 'XP remaining',
  'Registro do Sistema': 'System Record',
  'Sincronizando registros': 'Synchronizing records',
  'O Sistema ainda não registrou evolução hoje.': 'The System has not recorded any progression today.',
  'Ver missões disponíveis': 'View available quests',
  'Histórico de Evolução': 'Evolution History',
  'XP diário': 'daily XP',
  'Bônus semanal': 'Weekly bonus',
  'Protocolos': 'Protocols',
  'Modelos de treino': 'Workout Templates',
  'Dados e progresso': 'Data & progress',
  'Arsenal': 'Arsenal',
  'Nova Rotina': 'New Routine',
  'Importar Protocolo': 'Import Protocol',
  'Registrar Treino': 'Log Workout',
  '3x na semana': '3x per week',
  '4x na semana': '4x per week',
  '5x na semana': '5x per week',
  '6x na semana': '6x per week',
  'Treino em Casa': 'Home Workout',
  'A divisão clássica e mais eficiente para hipertrofia e força. Ideal para quem treina segundas, quartas e sextas.': 'The classic and most efficient division for hypertrophy and strength. Ideal for those who train Mon, Wed, and Fri.',
  'Divisão que permite maior volume semanal por grupo muscular e maior tempo de descanso. Excelente para intermediários.': 'Division that allows greater weekly volume per muscle group and more rest time. Excellent for intermediates.',
  'Foco em altíssima intensidade por grupo muscular com uma sessão por dia de segunda a sexta. Recomendado para caçadores avançados.': 'Focus on very high intensity per muscle group with one session per day from Monday to Friday. Recommended for advanced hunters.',
  'Volume e frequência máximos para atletas com rotina de treino dedicada. Duplica a divisão PPL cobrindo de segunda a sábado.': 'Maximum volume and frequency for athletes with a dedicated training routine. Duplicates PPL split covering Monday to Saturday.',
  'Programa completo utilizando apenas o peso do corpo. Excelente para manter a forma e consistência de qualquer lugar.': 'Complete program using only bodyweight. Excellent for maintaining form and consistency from anywhere.',
  'Treino completo de corpo inteiro com progressão simples, alta frequência e excelente recuperação.': 'Complete full-body workout with simple progression, high frequency and excellent recovery.',
  'Alternância eficiente entre membros superiores e inferiores para força e hipertrofia equilibradas.': 'Efficient alternation between upper and lower limbs for balanced strength and hypertrophy.',
  'Fundamentos de força com foco nos grandes levantamentos e progressão consistente de carga.': 'Strength fundamentals focusing on the big lifts and consistent load progression.',
  'Combina musculação e condicionamento para aumentar massa magra enquanto melhora o gasto energético.': 'Combines strength training and conditioning to build lean mass while improving energy expenditure.',
  '50-60 min por sessão': '50-60 min per session',
  '45-55 min por sessão': '45-55 min per session',
  '40-50 min por sessão': '40-50 min per session',
  '35-45 min por sessão': '35-45 min per session',
  '55-65 min por sessão': '55-65 min per session',
  '45-60 min por sessão': '45-60 min per session',
  'Membro': 'Member',
  'Equipamento': 'Equipment',
  'Filtros de Treino': 'Workout Filters',
  'Sessão Iniciada': 'Session Started',
  'Iniciar Sessão': 'Start Session',
  'Treino Ativo': 'Active Workout',
  'Concluir Treino': 'Finish Workout',
  'Abandonar Treino': 'Abandon Workout',
  'Série': 'Set',
  'Repetições': 'Reps',
  'Carga (kg)': 'Load (kg)',
  'Registrar Série': 'Log Set',
  'Séries concluídas': 'Completed sets',
  'Tempo de Descanso': 'Rest Time',
  'Descanso Ativo': 'Active Rest',
  'segundos': 'seconds',
  'Rotina concluída com sucesso!': 'Routine completed successfully!',
  'Treino registrado!': 'Workout registered!',
  'Mana': 'Mana',
  'Meta Calórica': 'Calorie Goal',
  'Consumido': 'Consumed',
  'Restante': 'Remaining',
  'Alimentos Registrados': 'Logged Foods',
  'Adicionar Alimento': 'Add Food',
  'Refeições': 'Meals',
  'Jantar': 'Dinner',
  'Ceia': 'Late Snack',
  'Lanche': 'Snack',
  'Calorias': 'Calories',
  'Carboidratos': 'Carbs',
  'Gorduras': 'Fats',
  'Gramas': 'Grams',
  'Kcal': 'Kcal',
  'Total Consumido': 'Total Consumed',
  'Meta diária': 'Daily Goal',
  'água': 'water',
  'Meta de Água': 'Water Goal',
  'ml': 'ml',
  'Copo (250ml)': 'Glass (250ml)',
  'Garrafa (500ml)': 'Bottle (500ml)',
  'Garrafa Grande (1L)': 'Large Bottle (1L)',
  'Zerar Diário': 'Reset Diary',
  'Códex da Alimentação': 'Food Codex',
  'Cardápios do Caçador': 'Hunter Meal Plans',
  'Recuperação de Mana': 'Mana Recovery',
  'Diário e Códex': 'Diary & Codex',
  'Biblioteca de Itens': 'Food Library',
  'Mana consumida': 'Mana consumed',
  'Qualidade do Sono': 'Sleep Quality',
  'Horas de Sono': 'Sleep Hours',
  'Hobbies': 'Hobbies',
  'Registrar Sono': 'Log Sleep',
  'Registrar Meditação': 'Log Meditation',
  'Registrar Lazer': 'Log Leisure',
  'Excelente': 'Excellent',
  'Bom': 'Good',
  'Regular': 'Fair',
  'Ruim': 'Poor',
  'Horas dormidas': 'Hours slept',
  'Minutos de meditação': 'Minutes of meditation',
  'Nível de estresse': 'Stress level',
  'Baixo': 'Low',
  'Médio': 'Medium',
  'Alto': 'High',
  'Restaurar energia e consistência': 'Restore energy and consistency',
  'Descanso': 'Rest',
  'Meditar': 'Meditate',
  'Minhas Finanças': 'My Finances',
  'Balanço Geral': 'Overall Balance',
  'Receitas': 'Income',
  'Despesas': 'Expenses',
  'Economias': 'Savings',
  'Objetivos Financeiros': 'Financial Goals',
  'Nova Transação': 'New Transaction',
  'Valor': 'Amount',
  'Entrada': 'Income',
  'Saída': 'Expense',
  'Investimento': 'Investment',
  'Poupança': 'Savings',
  'Salvar Transação': 'Save Transaction',
  'Nenhuma transação registrada.': 'No transactions recorded.',
  'Economizado': 'Saved',
  'Criar Objetivo': 'Create Goal',
  'Valor Alvo': 'Target Amount',
  'Objetivo criado com sucesso!': 'Goal created successfully!',
  'Transação registrada com sucesso!': 'Transaction logged successfully!',
  'Minha Fortuna': 'My Fortune',
  'Histórico Financeiro': 'Financial History',
  'Chefes derrotados': 'Defeated bosses',
  'Nenhum chefe derrotado ainda.': 'No bosses defeated yet.',
  'Dano': 'Damage',
  'Histórico de Combates': 'Combat History',
  'Ataque Crítico': 'Critical Strike',
  'Dano causado com sucesso!': 'Damage dealt successfully!',
  'Hábitos de Evolução': 'Evolution Habits',
  'Minhas Missões': 'My Quests',
  'Foco': 'Focus',
  'Atributo': 'Attribute',
  'Horário': 'Scheduled Time',
  'Frequência': 'Frequency',
  'Segunda': 'Monday',
  'Terça': 'Tuesday',
  'Quarta': 'Wednesday',
  'Quinta': 'Thursday',
  'Sexta': 'Friday',
  'Sábado': 'Saturday',
  'Domingo': 'Sunday',
  'Todos os dias': 'Every day',
  'Dias específicos': 'Specific days',
  'Concluir Quest': 'Complete Quest',
  'Deletar Quest': 'Delete Quest',
  'Nenhum hábito ativo.': 'No active habits.',
  'Nenhuma quest pendente.': 'No pending quests.',
  'Preferências': 'Preferences',
  'Dados da Conta': 'Account Data',
  'Apagar todos os dados': 'Reset all data',
  'Esta ação é irreversível!': 'This action is irreversible!',
  'Destruir Matriz': 'Destroy Matrix',
  'Redefinir Senha': 'Reset Password',
  'Senha Atual': 'Current Password',
  'Confirmar Nova Senha': 'Confirm New Password',
  'Senha alterada com sucesso!': 'Password changed successfully!',
  'Dados limpos com sucesso!': 'Data cleared successfully!',
  'Salvar Alterações': 'Save Changes',
  'HISTÓRICO DE RECUPERAÇÃO': 'RECOVERY HISTORY',
  'Regenere sua mana e calibre o atributo Equilíbrio (EQU).': 'Regenerate your mana and calibrate the Balance (BAL) attribute.',
  'Templo da Mente': 'Mind Temple',
  'Sono & Lazer': 'Sleep & Leisure',
  'registro de rest e hobbies': 'log of rest and hobbies',
  'registro de sono e hobbies': 'log of sleep and hobbies',
  'Lazer Offline': 'Offline Leisure',
  'Sono atual': 'Current sleep',
  'Lazer offline': 'Offline leisure',
  'meta diária: 8h': 'daily goal: 8h',
  'meta diária: 10 min': 'daily goal: 10 min',
  'meta diária: 60 min': 'daily goal: 60 min',
  'Média registrada: 6.0h': 'Average recorded: 6.0h',
  '0 min registrados hoje': '0 min logged today',
  '0 min longe das telas hoje': '0 min away from screens today',
  'Log Sleep': 'Log Sleep',
  'Informe duração e percepção de qualidade.': 'Enter duration and quality perception.',
  'Hours slept': 'Hours slept',
  'Qualidade do sono': 'Sleep quality',
  'Registrar rest': 'Log sleep',
  'Log Leisure': 'Log Leisure',
  'Registre uma pausa offline que ajudou sua recovery.': 'Log an offline break that helped your recovery.',
  'Duração em minutos': 'Duration in minutes',
  'Hobby ou atividade': 'Hobby or activity',
  'REPOUSO NOTURNO': 'NIGHT REST',
  '06/23 · QUALIDADE: 3/5': '06/23 · QUALITY: 3/5',
  '06/22 · LEITURA': '06/22 · READING',
  'HOBBY & DESCONEXÃO': 'HOBBY & DISCONNECTION',
  '06/22 · QUALIDADE: 3/5': '06/22 · QUALITY: 3/5',
  'GESTÃO DE RECURSOS': 'RESOURCE MANAGEMENT',
  'ATRIBUTO: WIS (SABEDORIA)': 'ATTRIBUTE: WIS (WISDOM)',
  'CONTROLE DE FLUXO DE MOEDAS E RITO DE INVESTIMENTOS PARA PURIFICAÇÃO DE DÍVIDAS.': 'COIN FLOW CONTROL AND INVESTMENT RITE FOR DEBT PURIFICATION.',
  'EARNED DO MÊS': 'EARNED THIS MONTH',
  'GASTOS DO MÊS': 'EXPENSES THIS MONTH',
  'APORTADO NO MÊS': 'INVESTED THIS MONTH',
  'APORTE / POUPANÇA': 'CONTRIBUTION / SAVINGS',
  'REGISTRAR FLUXO DE RECURSO': 'LOG RESOURCE FLOW',
  'DESCRIÇÃO': 'DESCRIPTION',
  'VALOR (R$)': 'AMOUNT (R$)',
  'TIPO': 'TYPE',
  'CATEGORIA': 'CATEGORY',
  'DATA': 'DATE',
  'Objetivos & Metas': 'Goals & Objectives',
  'QUEST DO SYSTEM': 'SYSTEM QUEST',
  'APORTE DE PURIFICAÇÃO (GUARDAR 20% DO EARNED)': 'PURIFICATION CONTRIBUTION (SAVE 20% OF EARNINGS)',
  'CALCULADO AUTOMATICAMENTE COM BASE NA RECEITA E NOS INVESTIMENTOS DESTE MÊS.': 'AUTOMATICALLY CALCULATED BASED ON INCOME AND INVESTMENTS OF THIS MONTH.',
  'REGISTROS DO MÊS ATUAL': 'CURRENT MONTH RECORDS',
  'AÇÃO': 'ACTION',
  'DESPESA': 'EXPENSE',
  'APORTE': 'INVESTMENT',
  'PROVÉRBIOS DA SABEDORIA (WIS)': 'PROVERBS OF WISDOM (WIS)',
  'Aporte de Proteção: Investidores consistentes mitigam o power do Mercador das Dívidas. Cada aporte causa dano crítico!': 'Protection Contribution: Consistent investors mitigate the power of the Debt Merchant. Each contribution deals critical damage!',
  'Aporte de Proteção: Investidores consistentes mitigam o poder do Mercador das Dívidas. Cada aporte causa dano crítico!': 'Protection Contribution: Consistent investors mitigate the power of the Debt Merchant. Each contribution deals critical damage!',
  'Healthy Contribution Rate: Procure direcionar pelo menos 20% da sua receita mensal para aportes ou reservas.': 'Healthy Contribution Rate: Try to direct at least 20% of your monthly income into contributions or savings.',
  'Healthy Contribution Rate: Procure direcionar pelo menos 20% da sua receita mensal para aportes ou reserva.': 'Healthy Contribution Rate: Try to direct at least 20% of your monthly income into contributions or savings.',
  'meta diária de recuperação': 'daily recovery goal',
  '1362 DE 1943 KCAL': '1362 OF 1943 KCAL',
  '581 kcal disponíveis para completar o goal de perder peso com consistência.': '581 kcal available to complete the goal of losing weight consistently.',
  'Sincronização energética': 'Energy synchronization',
  'Faixa recomendada': 'Recommended range',
  'XP previsto': 'Expected XP',
  'Referências de macros são estimativas visuais do System. A reward real é processada pela avaliação nutricional daily.': 'Macro references are visual estimates from the System. The real reward is processed by the daily nutritional assessment.',
  'Suporte físico': 'Physical support',
  'Proteína em faixa de referência': 'Protein in reference range',
  'Acompanha a preparação de FOR e RES sem conceder atributos automaticamente.': 'Monitors STR and END preparation without granting attributes automatically.',
  'reward daily': 'daily reward',
  'Concedidos pelo System no fechamento de um day dentro da faixa recomendada.': 'Granted by the System at the end of a day within the recommended range.',
  'Streak nutricional': 'Nutritional streak',
  'Sequência real de avaliações completed dentro da goal energética.': 'Real sequence of completed assessments within the energy goal.',
  'CÓDEX DA ALIMENTAÇÃO': 'FOOD CODEX',
  'Descreva sua meal e o System calculará calorias, macros e impacto na sua recovery.': 'Describe your meal and the System will calculate calories, macros, and impact on your recovery.',
  'Descrição da meal': 'Meal description',
  'Ex: Almocei 150g de filé de frango, 200g de arroz integral, 100g de feijão carioca e salada com uma colher de sopa de azeite...': 'Ex: I had 150g of chicken breast, 200g of brown rice, 100g of pinto beans, and salad with a tablespoon of olive oil...',
  'Prato completo': 'Full plate',
  'Período': 'Period',
  'CONSUMO DAILY': 'DAILY CONSUMPTION',
  'meal DE WHEY E AVEIA': 'WHEY AND OATS meal',
  'PRATO DE BATATA DOCE E FRANGO DESFRES...': 'SWEET POTATO AND SHREDDED CHICKEN PLATE...',
  'PRATO DE BANANA': 'BANANA PLATE',
  'PRATO DE BATATA DOCE E FRANGO DESF...': 'SWEET POTATO AND SHREDDED CHICKEN PLATE...',
};

const EXTRA_EXACT_ENGLISH: Record<string, string> = {
  // Global controls, modals, and legacy auth components
  'Selecionar idioma': 'Select language',
  'Sim': 'Yes',
  'Não': 'No',
  'NÃO': 'NO',
  'Abortar': 'Abort',
  'Categoria *': 'Category *',
  'Cor da categoria': 'Category color',
  'Cor personalizada': 'Custom color',
  'Stat alvo': 'Target stat',
  'XP por dia': 'XP per day',
  'Dias de Recorrência *': 'Recurrence days *',
  'Missão Flexível / Opcional': 'Flexible / Optional quest',
  'Se não fizer, não prejudica seu progresso de 100% no dia.': 'If you skip it, it will not hurt your 100% daily progress.',
  '⚠️ Erro de Calibração:': '⚠️ Calibration Error:',
  'Novo Hábito Diário': 'New Daily Habit',
  'Nome do hábito *': 'Habit name *',
  'Criar Hábito': 'Create Habit',
  'Criando...': 'Creating...',
  'Nova Quest': 'New Quest',
  'Título da quest *': 'Quest title *',
  'Chave da API do Groq (VITE_GROQ_API_KEY) não configurada no ambiente.': 'Groq API key (VITE_GROQ_API_KEY) is not configured in the environment.',
  'Usuário não autenticado': 'User not authenticated',
  'Usuário não autenticado.': 'User not authenticated.',
  'Mínimo 6 caracteres': 'Minimum 6 characters',
  'mínimo 6 caracteres': 'minimum 6 characters',
  'Confirmar Senha': 'Confirm Password',
  'Sua senha': 'Your password',
  'Manter conectado': 'Keep me signed in',
  'Ou': 'Or',
  'Novo Hunter?': 'New Hunter?',
  'Já despertou?': 'Already awakened?',
  'Já desperto?': 'Already awakened?',
  'Logar no sistema': 'Sign in to the System',
  'Logar sistema': 'Sign in to the System',
  'Acessar sistema': 'Access the System',
  'Despertar agora': 'Awaken now',
  'Despertar AGORA': 'AWAKEN NOW',
  'Despertar Hunter': 'Awaken Hunter',
  'Logar Sistema': 'Sign in to the System',
  'Entrando...': 'Signing in...',
  'Processando...': 'Processing...',
  'Processando despertar...': 'Processing awakening...',
  'As senhas não coincidem.': 'Passwords do not match.',
  'Senha mínima: 6 caracteres.': 'Minimum password length: 6 characters.',
  'Despertar Concluído!': 'Awakening Complete!',
  'Verifique seu email para confirmar seu rank e depois faça login.': 'Check your email to confirm your rank, then sign in.',
  'Sua jornada para o Rank S começa aqui.': 'Your journey to Rank S starts here.',
  'O sistema aguarda suas métricas.': 'The System awaits your metrics.',
  'A ascensão continua...': 'The ascension continues...',
  'Um novo despertar foi detectado.': 'A new awakening has been detected.',
  'Acompanhe sua própria evolução.': 'Track your own evolution.',
  'O sistema selecionou você.': 'The System selected you.',
  'Ocultar confirmação': 'Hide confirmation',
  'Mostrar confirmação': 'Show confirmation',
  'Iniciar Ascensão': 'Begin Ascension',
  'Já possui registro no sistema?': 'Already registered in the System?',
  'Primeira vez no sistema?': 'First time in the System?',
  'Prévia de status': 'Status preview',
  'Cada treino, refeição e decisão vira XP para a sua próxima versão.': 'Every workout, meal, and decision becomes XP for your next version.',

  // RPG attributes and achievements
  '⚔️ Força': '⚔️ Strength',
  '🧠 Inteligência': '🧠 Intelligence',
  '🛡️ Resistência': '🛡️ Endurance',
  '💚 Vitalidade': '💚 Vitality',
  '🔥 Disciplina': '🔥 Discipline',
  '📖 Sabedoria': '📖 Wisdom',
  '☯️ Equilíbrio': '☯️ Balance',
  'Você agora é um': 'You are now a',
  'Iniciante da Consistência': 'Consistency Initiate',
  'Guerreiro Diário': 'Daily Warrior',
  'Mestre da Rotina': 'Routine Master',
  'Mantenha uma streak de 3 dias seguidos': 'Maintain a 3-day streak',
  'Mantenha uma streak de 7 dias seguidos': 'Maintain a 7-day streak',
  'Mantenha uma streak de 15 dias seguidos': 'Maintain a 15-day streak',
  'Mantenha uma streak de 30 dias seguidos': 'Maintain a 30-day streak',
  'Força Absoluta': 'Absolute Strength',
  'Mente Brilhante': 'Brilliant Mind',
  'Inquebrável': 'Unbreakable',
  'Mente de Ferro': 'Iron Mind',
  'Olhar Aguçado': 'Keen Eye',
  'Alcance 20 pontos de Força': 'Reach 20 Strength points',
  'Alcance 20 pontos de Inteligência': 'Reach 20 Intelligence points',
  'Alcance 20 pontos de Resistência': 'Reach 20 Endurance points',
  'Alcance 20 pontos de Vitalidade': 'Reach 20 Vitality points',
  'Alcance 20 pontos de Disciplina': 'Reach 20 Discipline points',
  'Alcance 20 pontos de Sabedoria': 'Reach 20 Wisdom points',
  'Alcance 20 pontos de Equilíbrio': 'Reach 20 Balance points',
  'Constante': 'Steady',
  'Persistente': 'Persistent',
  'Inabalável': 'Unshakable',
  'Colosso': 'Colossus',
  'Arquimago': 'Archmage',
  'Bastião': 'Bastion',
  'Zenith': 'Zenith',
  'Eremita': 'Hermit',
  'Harmônico': 'Harmonic',

  // Command portal and dashboard leftovers
  '+1 Potência': '+1 Power',
  '+1 Fôlego': '+1 Stamina',
  'Foco Profundo': 'Deep Focus',
  '+1 Percepção': '+1 Perception',
  'Missão Principal': 'Main Quest',
  'Atualização em tempo real': 'Real-time update',
  'Domínio:': 'Domain:',
  'Sequência': 'Streak',
  'Visualize atributos, nível, rank e evolução dos domínios.': 'View attributes, level, rank, and domain progression.',
  'Análise Principal': 'Main Analysis',
  'Gerencie hábitos, tarefas e quests bônus da IA.': 'Manage habits, tasks, and AI bonus quests.',
  'Registre cargas, repetições e acompanhe sua evolução.': 'Log loads, reps, and track your progression.',

  // Product tour
  'MÓDULOS EXPANDIDOS': 'COMPLEMENTARY MODULES',
  'ASCENSÃO DO CAÇADOR': 'HUNTER ASCENSION',
  'Avançar': 'Next',
  'Pular': 'Skip',
  'Despertar': 'Awaken',

  // Nutrition and meal plans
  'Total energético dos cardápios': 'Total energy across meal plans',
  'refeição(ões) definida(s)': 'meal(s) defined',
  'Nova Refeição': 'New Meal',
  'Nenhum Cardápio Definido': 'No Meal Plan Defined',
  'Crie suas refeições para que apareçam como missões diárias.': 'Create meals so they appear as daily quests.',
  '+ Criar Primeira Refeição': '+ Create First Meal',
  'Defina seu cardápio': 'Define your meal plan',
  'Criar Refeição': 'Create Meal',
  'Ex: Café da Manhã, Ref. 1, Pré-Treino...': 'E.g. Breakfast, Meal 1, Pre-workout...',
  'Nenhum alimento adicionado ainda.': 'No food added yet.',
  'Nenhum alimento encontrado.': 'No food found.',
  'Adicionando...': 'Adding...',
  'Adicionar ao dia': 'Add to day',
  'Energia': 'Energy',
  'Dificuldade': 'Difficulty',
  'Preparo': 'Prep',
  'Carbos': 'Carbs',
  'Moderada': 'Moderate',
  'Estruturada': 'Structured',
  'Planejado': 'Planned',
  'Equilibrado': 'Balanced',
  'pré': 'pre',
  'pós': 'post',
  'Total Consumido': 'Total Consumed',
  'Refeições do Cardápio do Caçador devem ser ajustadas no próprio cardápio. Desmarque a missão antes de alterar os itens.': 'Hunter Meal Plan meals must be adjusted inside the meal plan itself. Uncheck the quest before changing items.',
  'A chave do Códex Neural (Groq API Key) não foi detectada no sistema. Por favor, configure a variável VITE_GROQ_API_KEY no arquivo .env.local.': 'The Neural Codex key (Groq API Key) was not detected in the system. Please configure VITE_GROQ_API_KEY in the .env.local file.',
  'Novo Alimento': 'New Food',
  'Nome descritivo em português, curto, em caixa alta (ex: PRATO DE ARROZ, FEIJÃO E FRANGO GRELHADO)': 'Short descriptive name in English, uppercase (e.g. RICE, BEANS, AND GRILLED CHICKEN PLATE)',
  'Prato completo': 'Full plate',
  'Análise concluída': 'Analysis complete',
  'Confiança estimada': 'Estimated confidence',
  'Ingredientes & Comparação de Fontes (TACO vs FatSecret vs IA)': 'Ingredients & Source Comparison (TACO vs FatSecret vs AI)',
  'Os macronutrientes da refeição foram calculados de forma consolidada comparando a Tabela TACO, base do FatSecret e estimativa da IA (fallback) para cada item individual. Revise os dados antes de registrar.': 'Meal macronutrients were calculated by comparing TACO, FatSecret, and AI fallback estimates for each item. Review the data before logging.',
  'XP diário pendente': 'Pending daily XP',
  'Salvar Registro': 'Save Record',
  'Porção (ex: 2)': 'Serving (e.g. 2)',

  // Workouts: general UI
  'Hoje': 'Today',
  'Missão física atual': 'Current physical mission',
  'Protocolos': 'Protocols',
  'Modelos de treino': 'Workout templates',
  'Evolução': 'Progression',
  'Dados e progresso': 'Data and progress',
  'Arsenal': 'Arsenal',
  'Biblioteca de exercícios': 'Exercise library',
  'Halteres': 'Dumbbells',
  'Barra': 'Barbell',
  'Máquina': 'Machine',
  'Peso corporal': 'Bodyweight',
  'Outros': 'Other',
  'Iniciante': 'Beginner',
  'Intermediário': 'Intermediate',
  'Avançado': 'Advanced',
  'Todos': 'All',
  'Nova Rotina': 'New Routine',
  'Importar Protocolo': 'Import Protocol',
  'Registrar Treino': 'Log Workout',
  'Novo Exercício': 'New Exercise',
  'Protocolo de Treinamento': 'Training Protocol',
  'Definir exercício': 'Set exercise',
  'Nome do Exercício *': 'Exercise Name *',
  'Grupo Muscular': 'Muscle Group',
  'Nome da Rotina': 'Routine Name',
  'Dias de Treino': 'Training Days',
  'Gerenciar': 'Manage',
  'Exercício Extra': 'Extra Exercise',
  'Finalizar Treino': 'Finish Workout',
  'Último Recorde': 'Last Record',
  'Marcar como Concluído': 'Mark as Complete',
  'Confirmar Exclusão': 'Confirm Deletion',
  'Tem certeza que deseja deletar o protocolo': 'Are you sure you want to delete protocol',
  'Esta ação é irreversível e removerá todos os dados vinculados.': 'This action is irreversible and will remove all linked data.',
  'Fechar detalhes do protocolo': 'Close protocol details',
  'Importando...': 'Importing...',
  'Importar Programa Completo': 'Import Full Program',
  'Programa importado com sucesso!': 'Program imported successfully!',
  'Este exercício já faz parte da rotina selecionada.': 'This exercise is already part of the selected routine.',
  'Não foi possível adicionar o exercício à rotina.': 'Could not add the exercise to the routine.',
  'Erro ao excluir rotina. Tente novamente.': 'Error deleting routine. Try again.',

  // Workout presets and exercise library terms
  '3x na semana': '3x per week',
  '4x na semana': '4x per week',
  '5x na semana': '5x per week',
  '6x na semana': '6x per week',
  'Treino em Casa': 'Home Workout',
  '50-60 min por sessão': '50-60 min per session',
  '45-55 min por sessão': '45-55 min per session',
  '40-50 min por sessão': '40-50 min per session',
  '35-45 min por sessão': '35-45 min per session',
  '55-65 min por sessão': '55-65 min per session',
  '45-60 min por sessão': '45-60 min per session',
  'Push Pull Legs 3x': 'Push Pull Legs 3x',
  'ABCD Hipertrofia': 'ABCD Hypertrophy',
  'ABCDE Clássico': 'Classic ABCDE',
  'Push Pull Legs 6x': 'Push Pull Legs 6x',
  'Full Body 3x': 'Full Body 3x',
  'Upper/Lower 4x': 'Upper/Lower 4x',
  'Força Base 3x': 'Base Strength 3x',
  'Recomposição Corporal': 'Body Recomposition',
  'A - Push (Empurrar)': 'A - Push',
  'B - Pull (Puxar)': 'B - Pull',
  'C - Legs (Pernas)': 'C - Legs',
  'A - Peito e Tríceps': 'A - Chest and Triceps',
  'B - Costas e Bíceps': 'B - Back and Biceps',
  'C - Pernas Completo': 'C - Complete Legs',
  'D - Ombros e Abdômen': 'D - Shoulders and Abs',
  'A - Peito': 'A - Chest',
  'B - Costas': 'B - Back',
  'C - Pernas': 'C - Legs',
  'D - Ombros': 'D - Shoulders',
  'E - Braços (Bíceps + Tríceps)': 'E - Arms (Biceps + Triceps)',
  'A - Push 1 (Empurrar)': 'A - Push 1',
  'B - Pull 1 (Puxar)': 'B - Pull 1',
  'C - Legs 1 (Pernas)': 'C - Legs 1',
  'D - Push 2 (Foco Isoladores)': 'D - Push 2 (Isolation Focus)',
  'E - Pull 2 (Foco Volume)': 'E - Pull 2 (Volume Focus)',
  'F - Legs 2 (Foco Posteriores)': 'F - Legs 2 (Posterior Focus)',
  'A - Superiores (Peso Corporal)': 'A - Upper Body (Bodyweight)',
  'B - Inferiores (Peso Corporal)': 'B - Lower Body (Bodyweight)',
  'C - Core e Cardio': 'C - Core and Cardio',
  'Full Body A': 'Full Body A',
  'Full Body B': 'Full Body B',
  'Full Body C': 'Full Body C',
  'Upper A - Força': 'Upper A - Strength',
  'Lower A - Força': 'Lower A - Strength',
  'Upper B - Volume': 'Upper B - Volume',
  'Lower B - Volume': 'Lower B - Volume',
  'Força A - Agachamento': 'Strength A - Squat',
  'Força B - Terra': 'Strength B - Deadlift',
  'Força C - Potência': 'Strength C - Power',
  'A - Superiores Metabólico': 'A - Metabolic Upper Body',
  'B - Inferiores Metabólico': 'B - Metabolic Lower Body',
  'C - Full Body': 'C - Full Body',
  'D - Condicionamento': 'D - Conditioning',
  'Peito': 'Chest',
  'Costas': 'Back',
  'Pernas': 'Legs',
  'Ombros': 'Shoulders',
  'Quadríceps': 'Quadriceps',
  'Posteriores': 'Hamstrings',
  'Panturrilhas': 'Calves',
  'Tríceps': 'Triceps',
  'Bíceps': 'Biceps',
  'Abdômen': 'Abs',
  'Antebraço': 'Forearm',
  'Força': 'Strength',
  'Flexibilidade': 'Flexibility',
  'Mobilidade': 'Mobility',
  'Supino Reto com Barra': 'Barbell Bench Press',
  'Supino Reto com Halteres': 'Dumbbell Bench Press',
  'Supino Inclinado com Barra': 'Incline Barbell Bench Press',
  'Supino Inclinado com Halteres': 'Incline Dumbbell Bench Press',
  'Desenvolvimento Militar': 'Military Press',
  'Desenvolvimento com Halteres': 'Dumbbell Shoulder Press',
  'Tríceps Pulley (Corda)': 'Rope Triceps Pushdown',
  'Tríceps Pulley (Barra)': 'Bar Triceps Pushdown',
  'Tríceps Testa': 'Skull Crusher',
  'Tríceps Francês': 'Overhead Triceps Extension',
  'Tríceps Banco (Cadeira)': 'Bench Triceps Dip',
  'Elevação Lateral': 'Lateral Raise',
  'Elevação Lateral na Polia': 'Cable Lateral Raise',
  'Elevação Lateral com Garrafas': 'Bottle Lateral Raise',
  'Elevação Frontal com Halteres': 'Dumbbell Front Raise',
  'Crucifixo Invertido': 'Reverse Fly',
  'Crucifixo Reto com Halteres': 'Flat Dumbbell Fly',
  'Crossover (Polia)': 'Cable Crossover',
  'Pec Deck (Voador)': 'Pec Deck Fly',
  'Levantamento Terra': 'Deadlift',
  'Puxada Alta (Pulley)': 'Lat Pulldown',
  'Puxada Triângulo (Pulley)': 'V-Bar Pulldown',
  'Remada Curvada com Barra': 'Bent-Over Barbell Row',
  'Remada Baixa (Triângulo)': 'Seated Cable Row (V-Bar)',
  'Remada Baixa (Cavalinho)': 'Low Row (T-Bar)',
  'Remada Unilateral com Halter': 'One-Arm Dumbbell Row',
  'Pull Down (Polia)': 'Cable Pulldown',
  'Rosca Direta com Barra W': 'EZ-Bar Curl',
  'Rosca Alternada com Halteres': 'Alternating Dumbbell Curl',
  'Rosca Concentrada': 'Concentration Curl',
  'Rosca Martelo com Halteres': 'Dumbbell Hammer Curl',
  'Rosca Martelo': 'Hammer Curl',
  'Rosca Inversa com Barra': 'Reverse Barbell Curl',
  'Encolhimento com Halteres': 'Dumbbell Shrug',
  'Agachamento Livre': 'Back Squat',
  'Agachamento Livre (Corporal)': 'Bodyweight Squat',
  'Agachamento Sumô com Halter': 'Dumbbell Sumo Squat',
  'Leg Press 45º': '45º Leg Press',
  'Cadeira Extensora': 'Leg Extension',
  'Mesa Flexora': 'Lying Leg Curl',
  'Cadeira Flexora': 'Seated Leg Curl',
  'Stiff com Barra': 'Barbell Romanian Deadlift',
  'Stiff com Halteres': 'Dumbbell Romanian Deadlift',
  'Panturrilhas em Pé': 'Standing Calf Raise',
  'Panturrilhas Sentado': 'Seated Calf Raise',
  'Panturrilhas Unilateral (Degrau)': 'Single-Leg Calf Raise (Step)',
  'Flexão de Braço (Solo)': 'Push-up (Floor)',
  'Flexão Inclinada (Apoio)': 'Incline Push-up',
  'Avanço / Passada': 'Lunge / Split Squat',
  'Elevação Pélvica (Solo)': 'Glute Bridge (Floor)',
  'Prancha Abdominal': 'Plank',
  'Abdominal Supra (Solo)': 'Crunch (Floor)',
  'Elevação de Pernas': 'Leg Raise',
  'Abdominal Remador': 'Seated V-up',
  'Polichinelos': 'Jumping Jacks',

  // Bosses, titles, and boss rewards
  'O Senhor da Procrastinação': 'The Lord of Procrastination',
  'Executor Implacável': 'Relentless Executor',
  'O Senhor da Procrastinação Derrotado': 'The Lord of Procrastination Defeated',
  'Purificou o Senhor da Procrastinação': 'Purified the Lord of Procrastination',
  'O Rei da Preguiça': 'The King of Sloth',
  'O Incansável': 'The Tireless One',
  'O Rei da Preguiça Derrotado': 'The King of Sloth Defeated',
  'Purificou o Rei da Preguiça': 'Purified the King of Sloth',
  'A Sereia da Distração': 'The Siren of Distraction',
  'A Sereia da Distração Derrotada': 'The Siren of Distraction Defeated',
  'Purificou a Sereia da Distração': 'Purified the Siren of Distraction',
  'Mestre do Foco': 'Master of Focus',
  'O Devorador do Progresso': 'The Devourer of Progress',
  'O Devorador do Progresso Derrotado': 'The Devourer of Progress Defeated',
  'Purificou o Devorador do Progresso': 'Purified the Devourer of Progress',
  'Mestre da Disciplina': 'Master of Discipline',
  'O Mercador das Dívidas': 'The Debt Merchant',
  'Guardião da Liberdade': 'Guardian of Freedom',
  'O Mercador das Dívidas Derrotado': 'The Debt Merchant Defeated',
  'Purificou o Mercador das Dívidas': 'Purified the Debt Merchant',
  'O Arauto do Caos': 'The Herald of Chaos',
  'O Arauto do Caos Derrotado': 'The Herald of Chaos Defeated',
  'Purificou o Arauto do Caos': 'Purified the Herald of Chaos',
  'Mestre da Clareza': 'Master of Clarity',
  'O Reflexo da Autossabotagem': 'The Reflection of Self-Sabotage',
  'Superou a si mesmo e purificou o Reflexo da Autossabotagem': 'Overcame yourself and purified the Reflection of Self-Sabotage',
  'CRÍTICO!': 'CRITICAL!',
  'Recompensas da Purificação': 'Purification Rewards',
  'Bônus de Experiência': 'Experience Bonus',
  'Título Desbloqueado': 'Title Unlocked',
  'Insígnia do Boss Derrotado': 'Defeated Boss Badge',
  'Purificar Entidade & Avançar': 'Purify Entity & Advance',
  'Multiplicador 1.75x para ações do tipo': '1.75x multiplier for actions of type',
  'Histórico de Dano': 'Damage History',
  'Nenhum impacto registrado nesta sessão.': 'No impact logged in this session.',
  'Recompensa da purificação': 'Purification reward',
  'Experiência': 'Experience',
  'Relíquia': 'Relic',
  'Insígnia do Boss': 'Boss Badge',
  'O ataque não pôde ser persistido. Sincronizando novamente...': 'The attack could not be saved. Synchronizing again...',
  'Completar tarefas diárias comuns e quests.': 'Complete common daily tasks and quests.',
  'Concluir treinos na aba Musculação (Workouts).': 'Complete workouts in the Strength Training tab.',
  'Hábitos e tarefas de Leitura, Estudo e Foco Profundo.': 'Reading, study, and deep-focus habits and tasks.',
  'Marcar refeições, manter metas nutricionais de calorias/água e sono no horário.': 'Check off meals, maintain calorie/water nutrition goals, and sleep on schedule.',
  'Hábitos de Finanças, controle de despesas e aportes de investimento.': 'Finance habits, expense control, and investment contributions.',
  'Planejamento semanal, metas de prioridade e organização de ambiente.': 'Weekly planning, priority goals, and environment organization.',
  'Manter a consistência diária ativa e streaks consecutivas longas.': 'Maintain active daily consistency and long streaks.',
  'Uma entidade gigantesca feita de correntes, relógios quebrados e fumaça negra. Ao seu redor existem centenas de missões abandonadas, projetos inacabados e metas esquecidas.': 'A gigantic entity made of chains, broken clocks, and black smoke. Around it lie hundreds of abandoned quests, unfinished projects, and forgotten goals.',
  'Com foco inabalável, você cortou as correntes e destruiu os relógios quebrados. O tempo agora pertence a você. Você se tornou um Executor Implacável!': 'With unshakable focus, you cut the chains and shattered the broken clocks. Time belongs to you now. You became a Relentless Executor!',
  'Uma criatura colossal sentada em um trono gigantesco de pedra e lodo. Ela não luta; apenas permanece imóvel. Correntes negras se espalham pelo chão, drenando a energia vital e a motivação de qualquer um que ouse se aproximar.': 'A colossal creature seated on a gigantic throne of stone and sludge. It does not fight; it simply remains still. Black chains spread across the floor, draining the life energy and motivation of anyone who dares approach.',
  'Seus treinos intensos e constância física fizeram o trono desmoronar e a letargia se dissipar. Nada pode parar o seu avanço!': 'Your intense workouts and physical consistency made the throne collapse and the lethargy dissolve. Nothing can stop your advance!',
  'Uma entidade etérea que flutua acima de um oceano digital formado por telas luminosas. Ao seu redor brilham notificações, redes sociais e vídeos curtos. Os caçadores hipnotizados ficam presos olhando para as telas enquanto sua energia vital é sugada.': 'An ethereal entity floating above a digital ocean of glowing screens. Around it shine notifications, social networks, and short videos. Hypnotized hunters remain trapped staring at screens while their life energy is drained.',
  'Você silenciou o ruído digital e recuperou sua atenção profunda. As luzes vazias não têm mais poder sobre a sua mente.': 'You silenced the digital noise and reclaimed your deep attention. The empty lights no longer have power over your mind.',
  'Uma criatura colossal e insaciável formada por energia escura e fragmentos de excessos, impulsos e gratificação imediata. Ele não destrói os caçadores por combate direto, mas os convence a abandonar seu potencial em troca de prazeres rápidos.': 'A colossal, insatiable creature formed from dark energy and fragments of excess, impulse, and instant gratification. It does not destroy hunters through direct combat; it convinces them to trade away their potential for quick pleasures.',
  'Sua rotina nutricional perfeita, controle calórico e hidratação enfraqueceram a criatura até que ela ficasse em silêncio. A disciplina é seu novo escudo.': 'Your perfect nutrition routine, calorie control, and hydration weakened the creature until it fell silent. Discipline is your new shield.',
  'Sentado dentro de um mercado dimensional infinito cheio de ouro e armaduras lendárias, o Mercador domina pela sedução. Ele nunca obriga ninguém; ele apenas oferece. Mas atrás de cada item fácil existe uma corrente invisível que prende sua liberdade futura.': 'Seated inside an infinite dimensional market filled with gold and legendary armor, the Merchant rules through temptation. He never forces anyone; he only offers. But behind every easy item is an invisible chain binding your future freedom.',
  'Ao registrar seus gastos e controlar suas compras por impulso, você quebrou o contrato dourado do Mercador e conquistou sua verdadeira liberdade.': 'By logging your spending and controlling impulse purchases, you broke the Merchant’s golden contract and claimed your true freedom.',
  'Uma catástrofe silenciosa. Ele não ataca com força física, mas transforma toda a sua vida em ruído e confusão. Sob sua influência, as prioridades somem, os planos se misturam e você acorda muito ocupado, mas nunca produtivo.': 'A silent catastrophe. It does not attack with physical force; it turns your life into noise and confusion. Under its influence, priorities vanish, plans blur together, and you wake up busy but never productive.',
  'Ao definir metas claras, planejar suas semanas e organizar sua rotina, o nevoeiro do Arauto se dissipou. O caminho agora está limpo.': 'By setting clear goals, planning your weeks, and organizing your routine, the Herald’s fog dispersed. The path is clear now.',
  'A origem de todos os males. Após derrotar todos os chefes anteriores, você alcança o último portal e encontra apenas um espelho. Dentro dele está você mesmo: a soma de todas as versões de você que desistiram no passado.': 'The origin of every evil. After defeating all previous bosses, you reach the final portal and find only a mirror. Inside it is you: the sum of every version of yourself that gave up in the past.',
  'Ao manter sua consistência e não desistir diante das dificuldades, você purificou a versão mais fraca de si mesmo. O sistema foi totalmente dominado.': 'By maintaining consistency and refusing to give up through difficulty, you purified the weaker version of yourself. The System has been fully mastered.',

  // Recovery, finances, and settings leftovers
  'EQUILÍBRIO': 'BALANCE',
  'Sessão de Meditação Cronometrada Concluída': 'Timed Meditation Session Completed',
  'Erro ao registrar sono:': 'Error logging sleep:',
  'Erro ao registrar meditação concluída:': 'Error logging completed meditation:',
  'Média registrada:': 'Recorded average:',
  'Foco calibrado': 'Focus calibrated',
  'Fenda de Anomalia': 'Anomaly Gate',
  'Fenda Aberta': 'Gate Open',
  'Portal Fechado': 'Portal Closed',
  'Gere uma quest bônus diária focada em um domínio.': 'Generate a daily bonus quest focused on one domain.',
  'Requer Chave do Despertar (Nível Premium)': 'Requires Awakening Key (Premium Level)',
  'Benefícios do Despertar Premium': 'Premium Awakening Benefits',
  'CONSUMO DIÁRIO': 'DAILY CONSUMPTION',
  'O Sistema ainda não detectou nutrientes hoje.': 'The System has not detected nutrients today.',
  'min registrados hoje': 'min logged today',
  'min longe das telas hoje': 'min away from screens today',
  'Histórico de': 'History of',
  'O Sistema ainda não detectou registros de recuperação.': 'The System has not detected recovery records yet.',
  'Registre sono, meditação ou lazer para iniciar sua trilha de equilíbrio.': 'Log sleep, meditation, or leisure to begin your balance trail.',
  'Duração em minutos': 'Duration in minutes',
  'HISTÓRICO DE RECUPERAÇÃO': 'RECOVERY HISTORY',
  'Regenere sua mana e calibre o atributo Equilíbrio (EQU).': 'Regenerate your mana and calibrate the Balance (BAL) attribute.',
  'Gestão de Recursos': 'Resource Management',
  'Controle de fluxo de moedas e rito de investimentos para purificação de dívidas.': 'Coin-flow control and investment rite for debt purification.',
  'Ganhos do Mês': 'Income This Month',
  'Gastos do Mês': 'Expenses This Month',
  'Aportado no Mês': 'Invested This Month',
  'Aporte / Poupança': 'Contribution / Savings',
  'Lançamento de': 'Entry of',
  'registrado.': 'logged.',
  'Registros do Mês Atual': 'Current Month Records',
  'Nenhum fluxo de moedas registrado este mês.': 'No coin flow logged this month.',
  'Ação': 'Action',
  'Meta Mensal (Ex: Investir 300 reais/mês)': 'Monthly Goal (e.g. Invest 300 reais/month)',
  'Quest do Sistema': 'System Quest',
  'Calculado automaticamente com base na receita e nos investimentos deste mês.': 'Automatically calculated from this month’s income and investments.',
  'Provérbios da Sabedoria (WIS)': 'Proverbs of Wisdom (WIS)',
  'Aporte de Proteção:': 'Protection Contribution:',
  'Investidores consistentes mitigam o poder do': 'Consistent investors weaken the power of the',
  'Cada aporte causa dano crítico!': 'Each contribution deals critical damage!',
  'Ex: Salário, Supermercado, Aporte FIIs...': 'E.g. Salary, Groceries, REIT contribution...',
  'Erro ao cadastrar transação:': 'Error creating transaction:',
  'Erro ao deletar transação:': 'Error deleting transaction:',
  'Diretrizes do Códex': 'Codex Guidelines',
  'Recorrência semanal': 'Weekly recurrence',
  'Próxima missão': 'Next mission',
  'Ciclo diário concluído': 'Daily cycle complete',
  'Amplia capacidade cognitiva e profundidade de foco.': 'Expands cognitive capacity and depth of focus.',
  'Reforça constância diária e fortitude mental.': 'Reinforces daily consistency and mental fortitude.',
  'Reforça a constância diária e a fortitude mental.': 'Reinforces daily consistency and mental fortitude.',
  'Bônus IA': 'AI Bonus',
  '[BÔNUS IA]': '[AI BONUS]',
  '[BÔNUS IA] ': '[AI BONUS] ',
  'Flexível': 'Flexible',
  'Editar quest': 'Edit quest',
  'Duração': 'Duration',
  'Divisão semanal': 'Weekly split',
  'Missão Física do Dia': 'Physical Quest of the Day',
  'Seu arsenal físico ainda está vazio': 'Your physical arsenal is still empty',
  'Crie um protocolo personalizado ou importe um modelo completo para iniciar sua evolução em FOR, VIT, RES e DIS.': 'Create a custom protocol or import a complete template to start your evolution in STR, VIT, END, and DIS.',
  'Adicionar ao treino': 'Add to workout',
  'Adicione à sua biblioteca de treino': 'Add it to your workout library',
  'Cadastrar Exercício': 'Create Exercise',
  'Selecione a rotina que receberá este exercício.': 'Select the routine that will receive this exercise.',
  '? Esta ação é irreversível e removerá todos os dados vinculados.': '? This action is irreversible and will remove all linked data.',
  'O Sistema ainda não registrou evolução física': 'The System has not logged physical progression yet',
  'Conclua sua primeira sessão para revelar volume, streak, recordes e grupos musculares mais treinados.': 'Complete your first session to reveal volume, streak, records, and most-trained muscle groups.',
  'Último:': 'Last:',
  'Inicie seu treinamento para capturar dados de evolução.': 'Start training to capture progression data.',
  'Diretrizes & Foco de Evolução': 'Growth Guidelines & Focus',
  'Selecione um foco...': 'Select a focus...',
  'Atualizar Registro': 'Update Profile',
  'Você consumiu': 'You consumed',
  'ultrapassando o limite recomendado de': 'exceeding the recommended limit of',
  'Faixa recomendada alcançada. O Sistema avaliará o resultado no fechamento do dia.': 'Recommended range reached. The System will evaluate the result at day close.',
  'Referências de macros são estimativas visuais do Sistema. A recompensa real é processada pela avaliação nutricional diária.': 'Macro references are visual estimates from the System. The real reward is processed by the daily nutrition assessment.',
  'Sequência real de avaliações concluídas dentro da meta energética.': 'Real streak of completed assessments within the energy goal.',
  'Descreva sua refeição e o Sistema calculará calorias, macros e impacto na sua recuperação.': 'Describe your meal and the System will calculate calories, macros, and recovery impact.',
  'Descrição da refeição': 'Meal description',
  '[Códex IA] Erro ao processar:': '[AI Codex] Error processing:',
  '[Códex IA] Erro ao registrar:': '[AI Codex] Error logging:',
  'Complete no perfil:': 'Complete in profile:',
  'dados físicos': 'physical data',
  'Templo do Silêncio': 'Temple of Silence',
  'Meditação Guiada': 'Guided Meditation',
  'Acalme sua mente para recuperar mana. Siga o pulso de respiração para sincronizar seus batimentos.': 'Calm your mind to recover mana. Follow the breathing pulse to synchronize your heartbeat.',
  'Título': 'Title',
  'Esta é a sua arte de vocação selada nas fendas profundas. Seu progresso, conquistas e reputação são espelhados em seus atributos de batalha diária.': 'This is your vocation art sealed in the deep rifts. Your progress, achievements, and reputation are mirrored in your daily battle attributes.',
  'Parâmetros Biométricos & Gênero': 'Biometrics & Gender',
  'Calibração de Atributos Físicos e Imagem no Perfil do Caçador': 'Physical attribute and Hunter profile image calibration',
  'Sexo (Gênero)': 'Sex (Gender)',
  'Definições de Metas de Treino, Carreira e Nível de Experiência': 'Training, career, and experience-level goal settings',
  'Selecione a experiência...': 'Select experience level...',
  'Desbloqueie Desafios e Equipe Títulos de Prestígio': 'Unlock challenges and equip prestige titles',
  'Títulos Desbloqueados': 'Unlocked Titles',
  'Atualizar Segurança': 'Update Security',
  'Diagnóstico': 'Diagnostics',
  '* Dica: Verifique se suas chaves do Supabase no Vercel/Ambiente de Produção estão preenchidas corretamente e possuem permissão nas tabelas.': '* Tip: Check whether your Supabase keys in Vercel/Production Environment are filled in correctly and have table permissions.',
  'SISTEMA DE SEGURANÇA ATUALIZADO: Suas novas chaves de acesso foram sincronizadas.': 'SECURITY SYSTEM UPDATED: Your new access keys were synchronized.',
  'Erro de autenticação.': 'Authentication error.',
  'FALHA DE REGISTRO CORRIGIDA: Seus atributos bônus e níveis de caçador foram purificados de volta ao Nível 1. Suas missões permanecem intactas.': 'REGISTRATION FAILURE CORRECTED: Your bonus attributes and hunter levels were purified back to Level 1. Your quests remain intact.',
  'Falha crítica ao limpar dados.': 'Critical failure while clearing data.',
  'Se você deseja recalibrar seus sensores cognitivos e rever a apresentação holográfica das seções e módulos vitais do aplicativo, re-inicie o protocolo de guia do caçador.': 'If you want to recalibrate your cognitive sensors and review the holographic presentation of the app sections and vital modules, restart the hunter guide protocol.',
  'Apaga permanentemente todos os treinos, refeições, tarefas, hábitos e históricos. Sua classe também será removida e o onboarding será reiniciado.': 'Permanently deletes all workouts, meals, tasks, habits, and history. Your class will also be removed and onboarding will restart.',
  'Você está prestes a redefinir seu nível de Caçador para 1, seu XP para 0 e todos os atributos RPG base para 10.': 'You are about to reset your Hunter level to 1, XP to 0, and all base RPG attributes to 10.',
  'Seus hábitos, treinos, tarefas e planos alimentares NÃO serão afetados!': 'Your habits, workouts, tasks, and meal plans will NOT be affected!',
  'Isso irá deletar de forma definitiva todos os seus treinos, rotinas, hábitos, tarefas, registros de comida e conquistas. Sua classe será apagada e você recomeçará do zero.': 'This will permanently delete all your workouts, routines, habits, tasks, food logs, and achievements. Your class will be erased and you will start from zero.',
  'Confirmar Destruição': 'Confirm Destruction',
};

const EXACT_ENGLISH: Record<string, string> = {
  ...BASE_EXACT_ENGLISH,
  ...EXTRA_EXACT_ENGLISH,
};

const RAW_REPLACEMENTS: Array<[string, string]> = [
  ['não autenticado', 'not authenticated'],
  ['forçando loading', 'forcing loading'],
  ['safety timeout disparado', 'safety timeout fired'],
  ['ao buscar', 'while fetching'],
  ['ao cadastrar', 'while creating'],
  ['ao deletar', 'while deleting'],
  ['ao atualizar', 'while updating'],
  ['ao registrar', 'while logging'],
  ['ao criar', 'while creating'],
  ['ao excluir', 'while deleting'],
  ['de conexão', 'connection'],
  ['conexão', 'connection'],
  ['dados financeiros', 'financial data'],
  ['metas financeiras', 'financial goals'],
  ['progresso da meta', 'goal progress'],
  ['no valor de', 'for'],
  ['este mês', 'this month'],
  ['do mês', 'this month'],
  ['mensal', 'monthly'],
  ['semana', 'week'],
  ['semanal', 'weekly'],
  ['recorrência', 'recurrence'],
  ['fluxo de moedas', 'coin flow'],
  ['rito de investimentos', 'investment rite'],
  ['purificação de dívidas', 'debt purification'],
  ['sessão de treino', 'workout session'],
  ['rotina selecionada', 'selected routine'],
  ['rotina excluída com sucesso', 'routine deleted successfully'],
  ['exclusão da rotina', 'routine deletion'],
  ['dados vinculados', 'linked data'],
  ['ação irreversível', 'irreversible action'],
  ['ações irreversíveis', 'irreversible actions'],
  ['senha atual', 'current password'],
  ['nova senha', 'new password'],
  ['confirmar senha', 'confirm password'],
  ['confirmar nova senha', 'confirm new password'],
  ['nome completo', 'full name'],
  ['nome do item', 'item name'],
  ['nome da refeição', 'meal name'],
  ['nome do exercício', 'exercise name'],
  ['nome da rotina', 'routine name'],
  ['grupo muscular', 'muscle group'],
  ['dias de treino', 'training days'],
  ['dias de recorrência', 'recurrence days'],
  ['cor da categoria', 'category color'],
  ['stat alvo', 'target stat'],
  ['sem horário', 'no scheduled time'],
  ['último recorde', 'last record'],
  ['último registro', 'last record'],
  ['registro do sistema', 'system record'],
  ['em preparação', 'being prepared'],
  ['em execução', 'in progress'],
  ['em progresso', 'in progress'],
  ['em breve', 'coming soon'],
  ['em faixa', 'in range'],
  ['em português', 'in Portuguese'],
  ['caixa alta', 'uppercase'],
  ['descrição livre', 'free-form description'],
  ['refeição(ões)', 'meal(s)'],
  ['alimento encontrado', 'food found'],
  ['cardápio definido', 'meal plan defined'],
  ['energia diária', 'daily energy'],
  ['consumo diário', 'daily consumption'],
  ['xp diário', 'daily XP'],
  ['bônus semanal', 'weekly bonus'],
  ['atributos principais', 'primary attributes'],
  ['foco profundo', 'deep focus'],
  ['missão principal', 'main quest'],
  ['missão física', 'physical quest'],
  ['módulo físico', 'physical module'],
  ['módulo fortuna', 'fortune module'],
  ['protocolo de treinamento', 'training protocol'],
  ['exercício extra', 'extra exercise'],
  ['peso corporal', 'bodyweight'],
  ['força base', 'base strength'],
  ['recomposição corporal', 'body recomposition'],
  ['condicionamento', 'conditioning'],
  ['potência', 'power'],
  ['percepção', 'perception'],
  ['fôlego', 'stamina'],
  ['domínio', 'domain'],
  ['sequência', 'streak'],
  ['título', 'title'],
  ['títulos', 'titles'],
  ['desafios', 'challenges'],
  ['prestígio', 'prestige'],
  ['segurança', 'security'],
  ['diagnóstico', 'diagnostics'],
  ['destruição', 'destruction'],
  ['purificação', 'purification'],
  ['insígnia', 'badge'],
  ['relíquia', 'relic'],
  ['crítico', 'critical'],
  ['experiência', 'experience'],
  ['habilidades', 'skills'],
  ['carreira', 'career'],
  ['gênero', 'gender'],
  ['sexo', 'sex'],
  ['biométricos', 'biometrics'],
  ['biométrico', 'biometric'],
  ['atributos físicos', 'physical attributes'],
  ['atributo físico', 'physical attribute'],
  ['caçadores', 'hunters'],
  ['chefes', 'bosses'],
  ['chefe', 'boss'],
  ['erro', 'error'],
  ['falha', 'failure'],
  ['usuário', 'user'],
  ['usuários', 'users'],
  ['ausente', 'missing'],
  ['ausentes', 'missing'],
  ['ambiente', 'environment'],
  ['variável', 'variable'],
  ['variáveis', 'variables'],
  ['configurada', 'configured'],
  ['configuradas', 'configured'],
  ['selecionar', 'select'],
  ['selecione', 'select'],
  ['defina', 'define'],
  ['definir', 'set'],
  ['verifique', 'check'],
  ['acesse', 'access'],
  ['iniciar', 'start'],
  ['inicie', 'start'],
  ['finalizar', 'finish'],
  ['marcar', 'mark'],
  ['crie', 'create'],
  ['criar', 'create'],
  ['registrar', 'log'],
  ['registre', 'log'],
  ['registro', 'record'],
  ['registros', 'records'],
  ['transações', 'transactions'],
  ['transação', 'transaction'],
  ['receitas', 'income'],
  ['receita', 'income'],
  ['despesas', 'expenses'],
  ['despesa', 'expense'],
  ['gastos', 'expenses'],
  ['ganhos', 'income'],
  ['poupança', 'savings'],
  ['aporte', 'contribution'],
  ['aportes', 'contributions'],
  ['investimentos', 'investments'],
  ['investimento', 'investment'],
  ['meditação', 'meditation'],
  ['lazer', 'leisure'],
  ['sono', 'sleep'],
  ['descanso', 'rest'],
  ['telas', 'screens'],
  ['média', 'average'],
  ['exclusão', 'deletion'],
  ['deletar', 'delete'],
  ['deletado', 'deleted'],
  ['apagado', 'deleted'],
  ['apaga', 'deletes'],
  ['redefinir', 'reset'],
  ['zerar', 'reset'],
  ['remover', 'remove'],
  ['removida', 'removed'],
  ['permanentemente', 'permanently'],
  ['definitiva', 'permanent'],
  ['senha', 'password'],
  ['chave', 'key'],
  ['chaves', 'keys'],
  ['email', 'email'],
  ['nome', 'name'],
  ['categoria', 'category'],
  ['categorias', 'categories'],
  ['dados', 'data'],
  ['tarefas', 'tasks'],
  ['tarefa', 'task'],
  ['rotinas', 'routines'],
  ['rotina', 'routine'],
  ['sessões', 'sessions'],
  ['sessão', 'session'],
  ['séries', 'sets'],
  ['série', 'set'],
  ['repetições', 'reps'],
  ['carga', 'load'],
  ['peso', 'weight'],
  ['altura', 'height'],
  ['valor', 'amount'],
  ['data', 'date'],
  ['período', 'period'],
  ['preparo', 'prep'],
  ['dificuldade', 'difficulty'],
  ['energia', 'energy'],
  ['proteína', 'protein'],
  ['proteínas', 'protein'],
  ['gorduras', 'fats'],
  ['carboidratos', 'carbs'],
  ['porção', 'serving'],
  ['ingredientes', 'ingredients'],
  ['confiança', 'confidence'],
  ['estimada', 'estimated'],
  ['estimado', 'estimated'],
  ['flexível', 'flexible'],
  ['opcional', 'optional'],
  ['personalizada', 'custom'],
  ['personalizado', 'custom'],
  ['indisponível', 'unavailable'],
  ['disponível', 'available'],
  ['nenhum', 'no'],
  ['nenhuma', 'no'],
  ['novo', 'new'],
  ['nova', 'new'],
  ['atuais', 'current'],
  ['atual', 'current'],
  ['própria', 'own'],
  ['próprio', 'own'],
  ['profundo', 'deep'],
  ['profunda', 'deep'],
  ['físicas', 'physical'],
  ['físicos', 'physical'],
  ['física', 'physical'],
  ['físico', 'physical'],
  ['não foi possível', 'could not'],
  ['ocorreu um erro', 'an error occurred'],
  ['tente novamente', 'try again'],
  ['tem certeza', 'are you sure'],
  ['deseja mesmo', 'do you really want to'],
  ['seu progresso', 'your progress'],
  ['sua progressão', 'your progression'],
  ['sua evolução', 'your evolution'],
  ['sua rotina', 'your routine'],
  ['sua meta', 'your goal'],
  ['seu objetivo', 'your goal'],
  ['nova refeição', 'new meal'],
  ['novo exercício', 'new exercise'],
  ['nova rotina', 'new routine'],
  ['novo hábito', 'new habit'],
  ['criar refeição', 'create meal'],
  ['criar rotina', 'create routine'],
  ['criar hábito', 'create habit'],
  ['adicionar ao dia', 'add to day'],
  ['adicionar alimento', 'add food'],
  ['buscar alimento', 'search food'],
  ['nenhum alimento', 'no food'],
  ['nenhuma refeição', 'no meal'],
  ['nenhum treino', 'no workout'],
  ['nenhuma rotina', 'no routine'],
  ['nenhuma missão', 'no quest'],
  ['missões', 'quests'],
  ['missão', 'quest'],
  ['refeições', 'meals'],
  ['refeição', 'meal'],
  ['treinamentos', 'training sessions'],
  ['treinamento', 'training'],
  ['treinos', 'workouts'],
  ['treino', 'workout'],
  ['hábitos', 'habits'],
  ['hábito', 'habit'],
  ['exercícios', 'exercises'],
  ['exercício', 'exercise'],
  ['cardápios', 'meal plans'],
  ['cardápio', 'meal plan'],
  ['alimentos', 'foods'],
  ['alimento', 'food'],
  ['caçador', 'Hunter'],
  ['sistema', 'System'],
  ['objetivos', 'goals'],
  ['objetivo', 'goal'],
  ['metas', 'goals'],
  ['meta', 'goal'],
  ['recompensas', 'rewards'],
  ['recompensa', 'reward'],
  ['progresso', 'progress'],
  ['evolução', 'progression'],
  ['recuperação', 'recovery'],
  ['nutrição', 'nutrition'],
  ['descanso', 'rest'],
  ['finanças', 'finances'],
  ['próximo nível', 'next level'],
  ['nível', 'level'],
  ['próxima', 'next'],
  ['próximo', 'next'],
  ['diárias', 'daily'],
  ['diários', 'daily'],
  ['diária', 'daily'],
  ['diário', 'daily'],
  ['concluídas', 'completed'],
  ['concluídos', 'completed'],
  ['concluída', 'completed'],
  ['concluído', 'completed'],
  ['pendentes', 'pending'],
  ['pendente', 'pending'],
  ['dias', 'days'],
  ['dia', 'day'],
  ['ganhos', 'earned'],
  ['ganho', 'earned'],
  ['restantes', 'remaining'],
  ['restante', 'remaining'],
  ['registrado', 'recorded'],
  ['registrada', 'recorded'],
  ['selecionado', 'selected'],
  ['selecionada', 'selected'],
  ['excluir', 'delete'],
  ['salvar', 'save'],
  ['cancelar', 'cancel'],
  ['confirmar', 'confirm'],
  ['adicionar', 'add'],
  ['editar', 'edit'],
  ['fechar', 'close'],
  ['voltar', 'back'],
  ['continuar', 'continue'],
  ['carregando', 'loading'],
  ['sincronizando', 'synchronizing'],
];

const REPLACEMENTS: Array<[RegExp, string]> = RAW_REPLACEMENTS.map(([word, replacement]) => {
  const escaped = word.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
  const regex = new RegExp('(?<![a-zA-ZáéíóúâêôãõçÁÉÍÓÚÂÊÔÃÕÇ])' + escaped + '(?![a-zA-ZáéíóúâêôãõçÁÉÍÓÚÂÊÔÃÕÇ])', 'gi');
  return [regex, replacement];
});

export function translateUiText(value: string) {
  const leading = value.match(/^\s*/)?.[0] ?? '';
  const trailing = value.match(/\s*$/)?.[0] ?? '';
  const text = value.trim();
  if (!text) return value;

  let translated = EXACT_ENGLISH[text] ?? text;
  if (translated === text) {
    for (const [pattern, replacement] of REPLACEMENTS) {
      translated = translated.replace(pattern, replacement);
    }
  }
  return `${leading}${translated}${trailing}`;
}
