const EXACT_ENGLISH: Record<string, string> = {
  'Sistema online': 'System online',
  'Sistema Online': 'System Online',
  'Bem-vindo ao Sistema': 'Welcome to the System',
  'Primeiro despertar': 'First Awakening',
  'Registre sua identidade e desbloqueie o protocolo de evolução.': 'Register your identity and unlock the evolution protocol.',
  'Acesse sua jornada de evolução, quests, bosses e progressão diária.': 'Access your journey of evolution, quests, bosses, and daily progression.',
  'Codinome': 'Codename',
  'Identidade': 'Identity',
  'Chave de acesso': 'Access key',
  'Confirmar chave': 'Confirm key',
  'Recuperar chave': 'Recover key',
  'Ocultar senha': 'Hide password',
  'Mostrar senha': 'Show password',
  'Ocultar confirmacao': 'Hide confirmation',
  'Mostrar confirmacao': 'Show confirmation',
  'Sincronizando...': 'Synchronizing...',
  'Despertar no Sistema': 'Awaken in the System',
  'Iniciar Ascensao': 'Begin Ascension',
  'Ja possui registro no sistema?': 'Already registered in the System?',
  'Primeira vez no sistema?': 'First time in the System?',
  'Acessar conta': 'Access account',
  'Solicitar despertar': 'Request awakening',
  'Gate calibrado': 'Gate calibrated',
  'Status preview': 'Status preview',
  'Classe': 'Class',
  'Boss da Semana': 'Weekly Boss',
  'Quests da comunidade': 'Community quests',
  'Mensagem do sistema': 'System message',
  'Transforme rotina em progressao visivel.': 'Turn routine into visible progression.',
  'Cada treino, refeicao e decisao vira XP para a sua proxima versao.': 'Every workout, meal, and decision becomes XP for your next version.',
  'Protocolo ativo': 'Active protocol',
  'XP para Level 13': 'XP to Level 13',
  'As senhas não coincidem': 'Passwords do not match',
  'Acesso restrito — Nível insuficiente.': 'Restricted access — Insufficient level.',

  'Calibração Biológica': 'Biological Calibration',
  'Protocolo de Identificação': 'Identification Protocol',
  'O Sistema precisa reconhecer o Caçador.': 'The System must recognize the Hunter.',
  'Sua assinatura inicial será gravada antes da abertura da primeira Fenda.': 'Your initial signature will be recorded before the first Gate opens.',
  'Nome do Caçador': 'Hunter Name',
  'Seu nome verdadeiro...': 'Your real name...',
  'Data de Nascimento': 'Date of Birth',
  'Sexo': 'Sex',
  'Masculino': 'Male',
  'Feminino': 'Female',
  'PRÓXIMO PASSO': 'NEXT STEP',
  'Análise Corporal': 'Body Analysis',
  'Varredura Biométrica': 'Biometric Scan',
  'O Sistema está lendo sua base física.': 'The System is reading your physical baseline.',
  'Cada métrica ajusta a dificuldade das primeiras missões.': 'Each metric adjusts the difficulty of your first missions.',
  'Altura (cm)': 'Height (cm)',
  'Peso Atual (kg)': 'Current Weight (kg)',
  'Peso Meta (kg)': 'Target Weight (kg)',
  'Objetivo Nutricional': 'Nutrition Goal',
  'Perder peso': 'Lose weight',
  'Manter peso': 'Maintain weight',
  'Ganhar peso': 'Gain weight',
  'Foco de Treino': 'Training Focus',
  'Musculação': 'Strength Training',
  'Funcional': 'Functional Training',
  'Esportes de Combate': 'Combat Sports',
  'Calistenia': 'Calisthenics',
  'Flexibilidade / Yoga': 'Flexibility / Yoga',
  'Missão Central': 'Core Mission',
  'O Sistema detectou múltiplos caminhos. Qual representa sua essência?': 'The System detected multiple paths. Which one represents your essence?',
  'Esta escolha define o primeiro eixo das suas quests de evolução.': 'This choice defines the first axis of your evolution quests.',
  'Evolução Geral': 'Overall Growth',
  'Quero crescer em todas as áreas da vida.': 'I want to grow in every area of life.',
  'Performance & Saúde': 'Performance & Health',
  'Foco em físico, energia e saúde duradoura.': 'Focus on fitness, energy, and lasting health.',
  'Independência Financeira': 'Financial Independence',
  'Construir riqueza e liberdade financeira real.': 'Build wealth and real financial freedom.',
  'Carreira & Habilidades': 'Career & Skills',
  'Dominar minha área e avançar na carreira.': 'Master my field and advance my career.',
  'Calibração de Rank': 'Rank Calibration',
  'Informe seu Rank inicial para calibrar a ameaça.': 'Enter your initial Rank to calibrate the threat.',
  'O Sistema ajustará as primeiras missões sem quebrar seu ritmo.': 'The System will adjust your first missions without disrupting your pace.',
  'Iniciante': 'Beginner',
  'Começando agora. Cada passo conta.': 'Starting now. Every step counts.',
  'Intermediário': 'Intermediate',
  'Tenho consistência. Quero ir além.': 'I am consistent. I want to go further.',
  'Avançado': 'Advanced',
  'Alta performance. Busco o limite máximo.': 'High performance. I seek the highest limit.',
  'AVANÇAR': 'CONTINUE',
  'Transmissão Recebida': 'Transmission Received',
  'Eu sou o Arquiteto.': 'I am the Architect.',
  'Fui eu quem construiu o sistema das Fendas. Fui eu quem deu a caçadores como Sung Jin-Woo uma segunda chance.': 'I built the Gate System. I gave hunters like Sung Jin-Woo a second chance.',
  'Agora, eu te ofereço a mesma oportunidade.': 'Now I offer you the same opportunity.',
  'Mas para calibrar seu poder, preciso entender do que você é feito.': 'But to calibrate your power, I need to understand what you are made of.',
  '"Responda com honestidade. O sistema não mente — e você também não deveria."': '"Answer honestly. The System does not lie—and neither should you."',
  'ACEITAR O DESAFIO': 'ACCEPT THE CHALLENGE',
  'Avaliação do Sistema': 'System Assessment',
  'Avaliação do Arquiteto': 'Architect Assessment',
  'REVELAR MEU CAMINHO': 'REVEAL MY PATH',
  'PRÓXIMA QUESTÃO': 'NEXT QUESTION',
  'Sistema de Avaliação · Solo Leveling': 'Assessment System · Solo Leveling',
  'Analisando Caçador...': 'Analyzing Hunter...',
  '"O sistema não escolhe os fracos. Ele revela os escolhidos."': '"The System does not choose the weak. It reveals the chosen."',
  'Resultado da Avaliação · Sistema do Arquiteto': 'Assessment Result · Architect System',
  'Classe despertada:': 'Awakened class:',
  'O Sistema identificou sua essência. Confirme o despertar ou escolha outro caminho antes de entrar na Fenda.': 'The System identified your essence. Confirm the awakening or choose another path before entering the Gate.',
  '"A fraqueza não é uma limitação. É um ponto de partida." — Arquiteto, Solo Leveling': '"Weakness is not a limitation. It is a starting point." — Architect, Solo Leveling',
  'Desbloqueado': 'Unlocked',
  'Conquista de despertar': 'Awakening achievement',
  'Atributos iniciais': 'Initial attributes',
  'Sua classe acabou de despertar.': 'Your class has just awakened.',
  'Recomendado': 'Recommended',
  'Em breve': 'Coming soon',
  'DESPERTAR PODER': 'AWAKEN POWER',
  'Evolução de Classe': 'Class Evolution',
  'Selecione o Nível de Rank': 'Select Rank Level',
  'Atributo & Potencial de Mana': 'Attribute & Mana Potential',
  'Use o seletor para vislumbrar seu poder futuro no Rank S.': 'Use the selector to glimpse your future power at Rank S.',

  'Perfil do Caçador': 'Hunter Profile',
  'Ver avatar': 'View avatar',
  'Sem classe': 'No class',
  'Título:': 'Title:',
  'Experiência do Hunter': 'Hunter Experience',
  'Próximo Rank': 'Next Rank',
  'Resumo de Hoje': 'Today Summary',
  'XP ganhos': 'XP earned',
  'Status de Hoje': 'Today Status',
  'XP acumulado hoje': 'XP earned today',
  'XP bônus não consome o limite diário': 'Bonus XP does not consume the daily limit',
  'Missões Diárias': 'Daily Quests',
  'Gerenciar Hábitos': 'Manage Habits',
  'Códex de Atividades': 'Activity Codex',
  'Nova Missão': 'New Quest',
  'Novo Hábito': 'New Habit',
  'Salvar': 'Save',
  'Cancelar': 'Cancel',
  'Excluir': 'Delete',
  'Editar': 'Edit',
  'Concluir': 'Complete',
  'Adicionar': 'Add',
  'Fechar': 'Close',
  'Voltar': 'Back',
  'Continuar': 'Continue',
  'Confirmar': 'Confirm',
  'Carregando...': 'Loading...',
  'Nenhum registro encontrado.': 'No records found.',
  'Hoje': 'Today',
  'Ontem': 'Yesterday',
  'Ativo': 'Active',
  'Inativo': 'Inactive',
  'Todos': 'All',
  'Buscar': 'Search',
  'Recompensa': 'Reward',
  'Progresso': 'Progress',
  'Meta': 'Goal',
  'Metas': 'Goals',
  'Treinos': 'Workouts',
  'Exercícios': 'Exercises',
  'Rotinas': 'Routines',
  'Evolução': 'Progression',
  'Histórico': 'History',
  'Recuperação': 'Recovery',
  'Alimentação': 'Nutrition',
  'Finanças': 'Finances',
  'Sono': 'Sleep',
  'Meditação': 'Meditation',
  'Lazer': 'Leisure',
  'Força': 'Strength',
  'Inteligência': 'Intelligence',
  'Resistência': 'Endurance',
  'Vitalidade': 'Vitality',
  'Disciplina': 'Discipline',
  'Sabedoria': 'Wisdom',
  'Equilíbrio': 'Balance',
  'Força Vital': 'Vital Force',
  'Ritmo de Evolução': 'Evolution Pace',
  'Ritmo elevado. Sua progressão diária está consistente.': 'High pace. Your daily progression is consistent.',
  'Potencial disponível. Complete novas ações para fortalecer sua ficha.': 'Potential available. Complete new actions to strengthen your profile.',
  'Quest diária recomendada': 'Recommended daily quest',
  'Missão física prioritária': 'Priority physical mission',
  'Próxima quest em preparação': 'Next quest being prepared',
  'Todas as missões de hoje foram concluídas.': 'All of today’s quests are complete.',
  'Abrir missões': 'Open quests',
  'Iniciar missão': 'Start quest',
  'Ver missão': 'View quest',
  'Aguardando evolução': 'Awaiting progression',
  'Progresso diário': 'Daily progress',
  'Protocolo de recuperação': 'Recovery protocol',
  'Treino concluído': 'Workout completed',
  'Refeição registrada': 'Meal recorded',
  'Finanças atualizadas': 'Finances updated',
  'Sequência mantida': 'Streak maintained',
  'Sem variação hoje': 'No change today',
  'Não definida': 'Not defined',
  'Máximo': 'Maximum',
  'Parâmetros do Sistema': 'System Parameters',
  'Complete uma missão para gerar seu primeiro registro.': 'Complete a quest to generate your first record.',
  'Avatar ampliado do Caçador': 'Enlarged Hunter avatar',

  'Códex do Caçador': 'Hunter Codex',
  'Ciclo diário concluído': 'Daily cycle complete',
  'Sistema sincronizado. Todas as quests do ciclo foram concluídas.': 'System synchronized. Every quest in this cycle is complete.',
  'Automática': 'Automatic',
  'diretriz disponível': 'directive available',
  'diretrizes disponíveis': 'directives available',
  'Concluída': 'Completed',
  'EM EXECUÇÃO': 'IN PROGRESS',
  'MISSÃO CONCLUÍDA': 'QUEST COMPLETED',
  'ANOMALIA CONCLUÍDA': 'ANOMALY COMPLETED',
  'TREINO CONCLUÍDO': 'WORKOUT COMPLETED',
  'REFEIÇÃO FEITA': 'MEAL COMPLETED',
  'Abrir módulo': 'Open module',
  'Deletar missão permanente': 'Permanently delete quest',
  'Registrar Operações Financeiras do Dia': 'Log Today’s Financial Operations',
  'Refeições Saudáveis': 'Healthy Meals',
  'Treino de Força': 'Strength Training',
  'Trabalhar (Foco Diário)': 'Work (Daily Focus)',
  'Trabalhar (Foco Máximo)': 'Work (Maximum Focus)',
  'Programação & Tech': 'Programming & Tech',
  'Tocar Instrumento / Música': 'Play Instrument / Music',
  'ALIMENTAÇÃO': 'NUTRITION',
  'FINANÇAS': 'FINANCES',
  'FORÇA': 'STRENGTH',
  'INTELIGÊNCIA': 'INTELLIGENCE',
  'RESISTÊNCIA': 'ENDURANCE',
  'Força (FOR)': 'Strength (STR)',
  'Inteligência (INT)': 'Intelligence (INT)',
  'Resistência (RES)': 'Endurance (END)',
  'Saúde': 'Health',
  'Sem horário': 'No scheduled time',
  'Falha na conexão neural com o Groq.': 'Neural connection to Groq failed.',
  'Apoia energia, recuperação e consistência nutricional.': 'Supports energy, recovery, and nutritional consistency.',
  'Eleva a capacidade física e consolida progressão de cargas.': 'Raises physical capacity and consolidates load progression.',
  'Aprimora condicionamento e capacidade de sustentar esforço.': 'Improves conditioning and sustained effort capacity.',
  'Fortalece constância profissional e execução sob pressão.': 'Strengthens professional consistency and execution under pressure.',
  'Amplia autonomia, entrega e resiliência profissional.': 'Expands autonomy, delivery, and professional resilience.',
  'Expande repertório, memória e adaptação cognitiva.': 'Expands repertoire, memory, and cognitive adaptability.',
  'Fortalece raciocínio sistêmico e solução de problemas.': 'Strengthens systems thinking and problem-solving.',
  'Promove expressão criativa e equilíbrio mental.': 'Promotes creative expression and mental balance.',
  'Reforça manutenção, autocuidado e progresso sustentável.': 'Reinforces maintenance, self-care, and sustainable progress.',

  'Biblioteca de exercícios': 'Exercise Library',
  'Buscar exercício ou grupo muscular...': 'Search exercise or muscle group...',
  'Novo Exercício': 'New Exercise',
  'Definir exercício': 'Set exercise',
  'Nome do Exercício *': 'Exercise Name *',
  'Este exercício já faz parte da rotina selecionada.': 'This exercise is already part of the selected routine.',
  'Não foi possível adicionar o exercício à rotina.': 'Could not add the exercise to the routine.',
  'Deseja mesmo abandonar o treino atual? Seu progresso nesta sessão será perdido.': 'Do you really want to abandon the current workout? This session’s progress will be lost.',
  'Rotina excluída com sucesso': 'Routine deleted successfully',
  'Evolução física estruturada': 'Structured physical progression',
  'Missão de hoje': 'Today’s mission',
  'Missão física atual': 'Current physical mission',
  'Base muscular e consistência': 'Muscular foundation and consistency',
  'Hipertrofia com recuperação': 'Hypertrophy with recovery',
  'Volume e frequência máxima': 'Maximum volume and frequency',
  'Especialização muscular': 'Muscle specialization',
  'Massa magra e gasto energético': 'Lean mass and energy expenditure',
  'Progressão de força': 'Strength progression',
  'Potência': 'Power',
  'Glúteos': 'Glutes',
  'Tríceps': 'Triceps',
  'Bíceps': 'Biceps',
  'Máquina': 'Machine',

  'Café da Manhã': 'Breakfast',
  'Almoço': 'Lunch',
  'Café da Tarde': 'Afternoon Snack',
  'Café proteico': 'Protein Coffee',
  'Lanche rápido': 'Quick Snack',
  'Nome da refeição': 'Meal name',
  'Registrar no diário': 'Log in diary',
  'Confirmar Recuperação': 'Confirm Recovery',
  'Concluir edição': 'Finish editing',
  'Descreva a refeição para que o Códex possa calibrar.': 'Describe the meal so the Codex can calibrate it.',
  'Registre uma refeição para iniciar sua recuperação de mana.': 'Log a meal to begin your mana recovery.',
  'Não foi possível registrar a refeição. Tente novamente.': 'The meal could not be logged. Try again.',
  'Não foi possível concluir a refeição.': 'The meal could not be completed.',
  'Houve uma anomalia na calibração neural. Tente novamente.': 'There was an anomaly in neural calibration. Try again.',
  'A referência diária foi ultrapassada. Siga normalmente e priorize consistência ao longo dos dias.': 'The daily reference was exceeded. Continue normally and prioritize consistency over time.',
  'Energia diária': 'Daily energy',
  'Meta indisponível': 'Goal unavailable',
  'Alimento indisponível': 'Food unavailable',
  'Disponível': 'Available',
  'Proteína': 'Protein',
  'Proteínas': 'Protein',
  'Porção (ex: 2)': 'Serving (e.g. 2)',
  'Kcal por porção/100g': 'Kcal per serving/100g',

  'Registrar Transação': 'Log Transaction',
  'Descrição': 'Description',
  'Despesa (Saída)': 'Expense (Outflow)',
  'Título do Objetivo': 'Goal Title',
  'Meta Única (Ex: Comprar Carro)': 'One-Time Goal (e.g. Buy a Car)',
  'Objetivo Único': 'One-Time Goal',
  'Reserva de Emergência': 'Emergency Fund',
  'Salário': 'Salary',
  'Ações': 'Actions',
  'Excluir transação': 'Delete transaction',
  'Por favor, preencha a descrição e um valor maior que zero.': 'Please enter a description and an amount greater than zero.',
  'Por favor, insira o título e o valor alvo da meta.': 'Please enter the goal title and target amount.',
  'Erro ao registrar transação no Supabase.': 'Error logging transaction in Supabase.',
  'Erro ao excluir a transação.': 'Error deleting transaction.',

  'Estado de equilíbrio': 'Balance state',
  'Equilíbrio restaurado': 'Balance restored',
  'Mana em recuperação': 'Mana recovering',
  'Recuperação em progresso': 'Recovery in progress',
  'Meta alcançada': 'Goal reached',
  'Desconexão completa': 'Complete disconnection',
  'Hobby & Desconexão': 'Hobby & Disconnection',
  'Meditação / Calma': 'Meditation / Calm',
  'Meditação acumulada': 'Accumulated meditation',
  'Sem observações': 'No notes',
  'Ex: Leitura, Violão, Caminhada...': 'E.g. Reading, Guitar, Walking...',
  'respiração, meditação e foco': 'breathing, meditation, and focus',

  'Nome do hábito *': 'Habit name *',
  'Título da quest *': 'Quest title *',
  'Horário (Opcional)': 'Time (Optional)',
  'Criar Hábito': 'Create Habit',
  'Ex: Estudo, Treino, Saúde, Mindset...': 'E.g. Study, Workout, Health, Mindset...',
  'Ex: Estudo, Treino, Hábito...': 'E.g. Study, Workout, Habit...',
  'Exercício Desconhecido': 'Unknown Exercise',
  'Alto em proteína': 'High protein',
  'Energia e reposição': 'Energy and replenishment',
  'Equilíbrio e consistência': 'Balance and consistency',
  'Expandir cardápio': 'Expand meal plan',
  'Recolher cardápio': 'Collapse meal plan',
  'Pós-treino': 'Post-workout',
  'Pré-treino': 'Pre-workout',
  'Suporte à força e recuperação': 'Strength and recovery support',
  'Rápido': 'Quick',
  'Fácil': 'Easy',
  'Nenhum': 'None',
  'Nenhuma': 'None',
  'Nenhum registro': 'No records',
  'Buscar...': 'Search...',
  'Criar Quest': 'Create Quest',
  'Criando...': 'Creating...',
  'Novo': 'New',
  'Nova': 'New',
  'Novo valor': 'New amount',
  'Módulo Físico': 'Physical Module',
  'Módulo Fortuna': 'Fortune Module',
  'Boss disponível': 'Boss available',
  'Classe não definida': 'Class not selected',
  'Estudar Novo Idioma': 'Study a New Language',
  'Buscar suprimentos nutricionais...': 'Search nutritional supplies...',
  'Multiplicador ativo': 'Active multiplier',
  'Disponível amanhã': 'Available tomorrow',
  '1 uso disponível': '1 use available',
  'O dano principal é aplicado automaticamente ao concluir atividades nos módulos do Ascend.': 'Main damage is applied automatically when activities are completed in Ascend modules.',
  'Golpe crítico · multiplicador ativo': 'Critical strike · active multiplier',
  'Acesso restrito — Faça login para entrar na fenda.': 'Restricted access — Sign in to enter the Gate.',
  'Falha ao sincronizar a fenda': 'Failed to synchronize the Gate',
  'Erro ao sincronizar com o banco.': 'Failed to synchronize with the database.',
  'Formato de dados incompleto retornado pelo modelo de IA.': 'The AI model returned incomplete data.',
  'Falha ao registrar sono.': 'Failed to log sleep.',
  'Falha ao registrar lazer.': 'Failed to log leisure.',
  'A sincronização do Codex expirou. O banco de dados pode estar lento ou inacessível.': 'Codex synchronization timed out. The database may be slow or unavailable.',
  'A conexão de telemetria expirou. O banco de dados pode estar lento ou inacessível.': 'Telemetry connection timed out. The database may be slow or unavailable.',
  'Nenhuma credencial nova foi informada.': 'No new credentials were provided.',
  'Dados de Identidade Opcionais no Codex': 'Optional Identity Data in the Codex',
  'Nova Senha': 'New Password',
  'Ação totalmente irreversível!': 'This action is completely irreversible!',
  'Purificar Atributos?': 'Purify Attributes?',
  'Senha': 'Password',
  'Sua senha': 'Your password',
  'Entrar': 'Sign in',
  'Já despertou?': 'Already awakened?',
  'Novo Hunter?': 'New Hunter?',
  'Senha mínima: 6 caracteres.': 'Minimum password length: 6 characters.',
  'Um novo despertar foi detectado.': 'A new awakening has been detected.',
  'Criar é Evoluir': 'To Create Is to Evolve',
  'Classe determinada pelo Arquiteto.': 'Class determined by the Architect.',
  'Despertar da Classe': 'Class Awakening',
  'Acessar módulo': 'Open module',
  'Energia': 'Energy',
  'Energia (kcal)': 'Energy (kcal)',
  'Dificuldade': 'Difficulty',
  'Preparo': 'Preparation',
  'Cor personalizada': 'Custom color',
  'FICHA DE INTEGRAÇÃO': 'NEURAL INTEGRATION',
  'Canalizando Energia...': 'Channeling Energy...',
  'Descrição do Boss': 'Boss Description',
  'Regeneração': 'Regeneration',
  'Desfazer atividades restaura o mesmo dano aplicado, impedindo farm de golpes.': 'Undoing activities restores the same damage dealt, preventing attack farming.',
  'Nenhuma raid ativa encontrada na fenda.': 'No active raid found in the Gate.',
  'Eventos recentes registrados durante esta sessão de raid.': 'Recent events recorded during this raid session.',
  'Regeneração de HP': 'HP Regeneration',
  'Registro de todos os chefes derrotados no servidor do ASCEND': 'Record of every boss defeated on the ASCEND server',
  'Registrando no Codex...': 'Recording in the Codex...',
  'Ex: Guardar 40 mil para o carro': 'E.g. Save 40,000 for a car',
  'Nenhuma resposta retornada do modelo de IA.': 'The AI model returned no response.',
  'Complete no perfil:': 'Complete in profile:',
  'Criar quest': 'Create quest',
  'Faltam no perfil:': 'Missing from profile:',
  'Acelera a regeneração celular e a imunidade biológica.': 'Accelerates cellular regeneration and biological immunity.',
  'Eleva o dano físico bruto e a densidade miofibrilar.': 'Raises raw physical damage and myofibrillar density.',
  'Otimiza o fluxo de oxigênio e a capacidade cardiovascular.': 'Optimizes oxygen flow and cardiovascular capacity.',
  'Fortalece a constância profissional e a entrega sob pressão.': 'Strengthens professional consistency and delivery under pressure.',
  'Esforço adicional que eleva sua autonomia financeira e resiliência.': 'Additional effort that increases financial autonomy and resilience.',
  'O Corpo é a Arma': 'The Body Is the Weapon',
  'A Mente é o Campo de Batalha': 'The Mind Is the Battlefield',
  'O Equilíbrio é Poder': 'Balance Is Power',
  'Calibração de Identidade': 'Identity Calibration',
  'A fraqueza não é uma limitação. É um ponto de partida.': 'Weakness is not a limitation. It is a starting point.',
  'Nome de Batismo (Codinome Real)': 'Given Name (Real Codename)',
  'Títulos liberados ao conquistar marcos importantes. Escolha um para exibir no seu perfil.': 'Titles unlocked by reaching major milestones. Choose one to display on your profile.',
  'Modificação de Chaves Criptográficas': 'Cryptographic Key Modification',
  'Calibração de Interface e Guias Virtuais': 'Interface Calibration and Virtual Guides',
  'Conexão Supabase': 'Supabase Connection',
  'Anomalia de Conexão Detectada': 'Connection Anomaly Detected',
  'Registros na Nuvem (Sincronização)': 'Cloud Records (Synchronization)',
  'Sincronização Forçada': 'Forced Synchronization',
  'Ações Irreversíveis de Modificação de Matriz': 'Irreversible Matrix Modification Actions',
  'Destruição da Matriz!': 'Matrix Destruction!',
  'VALIDAÇÃO FALHOU: As senhas digitadas não coincidem.': 'VALIDATION FAILED: The passwords do not match.',
  'REGISTRO ATUALIZADO: Sua identidade no Codex foi gravada com sucesso.': 'RECORD UPDATED: Your identity was successfully recorded in the Codex.',
  '+ XP hoje': '+ XP today',
  '+ hoje': '+ today',
  'Hunter em uma fenda de energia do Ascend System': 'Hunter inside an Ascend System energy Gate',
  'Transforme rotina em progressão visível.': 'Turn routine into visible progression.',
  'ERRO DE GRAVAÇÃO:': 'WRITE ERROR:',
  'ERRO DE SEGURANÇA:': 'SECURITY ERROR:',
  'ERRO DE REDEFINIÇÃO:': 'RESET ERROR:',
  'ERRO DE RESET COMPLETO:': 'FULL RESET ERROR:',
  'Classe atual': 'Current class',
  'Módulo': 'Module',
  'Categoria': 'Category',
  'Taxa de Aporte Saudável:': 'Healthy Contribution Rate:',
  'Conversão de energia': 'Energy conversion',
  'Nome do item': 'Item name',
  'Ir para Módulo': 'Go to Module',
  'Nome da Rotina': 'Routine Name',
  'Esta ação é irreversível e removerá todos os dados vinculados.': 'This action is irreversible and will remove all linked data.',
  'Esqueceu a senha?': 'Forgot your password?',
  'Volume Total': 'Total Volume',
};

const REPLACEMENTS: Array<[RegExp, string]> = [
  [/\berro\b/gi, 'error'],
  [/\bfalha\b/gi, 'failure'],
  [/\bnão foi possível\b/gi, 'could not'],
  [/\bocorreu um erro\b/gi, 'an error occurred'],
  [/\btente novamente\b/gi, 'try again'],
  [/\btem certeza\b/gi, 'are you sure'],
  [/\bdeseja mesmo\b/gi, 'do you really want to'],
  [/\bseu progresso\b/gi, 'your progress'],
  [/\bsua progressão\b/gi, 'your progression'],
  [/\bsua evolução\b/gi, 'your evolution'],
  [/\bsua rotina\b/gi, 'your routine'],
  [/\bsua meta\b/gi, 'your goal'],
  [/\bseu objetivo\b/gi, 'your goal'],
  [/\bnova refeição\b/gi, 'new meal'],
  [/\bnovo exercício\b/gi, 'new exercise'],
  [/\bnova rotina\b/gi, 'new routine'],
  [/\bnovo hábito\b/gi, 'new habit'],
  [/\bcriar refeição\b/gi, 'create meal'],
  [/\bcriar rotina\b/gi, 'create routine'],
  [/\bcriar hábito\b/gi, 'create habit'],
  [/\badicionar ao dia\b/gi, 'add to day'],
  [/\badicionar alimento\b/gi, 'add food'],
  [/\bbuscar alimento\b/gi, 'search food'],
  [/\bnenhum alimento\b/gi, 'no food'],
  [/\bnenhuma refeição\b/gi, 'no meal'],
  [/\bnenhum treino\b/gi, 'no workout'],
  [/\bnenhuma rotina\b/gi, 'no routine'],
  [/\bnenhuma missão\b/gi, 'no quest'],
  [/\bmissões\b/gi, 'quests'],
  [/\bmissão\b/gi, 'quest'],
  [/\brefeições\b/gi, 'meals'],
  [/\brefeição\b/gi, 'meal'],
  [/\btreinamentos\b/gi, 'training sessions'],
  [/\btreinamento\b/gi, 'training'],
  [/\btreinos\b/gi, 'workouts'],
  [/\btreino\b/gi, 'workout'],
  [/\bhábitos\b/gi, 'habits'],
  [/\bhábito\b/gi, 'habit'],
  [/\bexercícios\b/gi, 'exercises'],
  [/\bexercício\b/gi, 'exercise'],
  [/\bcardápios\b/gi, 'meal plans'],
  [/\bcardápio\b/gi, 'meal plan'],
  [/\balimentos\b/gi, 'foods'],
  [/\balimento\b/gi, 'food'],
  [/\bcaçador\b/gi, 'Hunter'],
  [/\bsistema\b/gi, 'System'],
  [/\bobjetivos\b/gi, 'goals'],
  [/\bobjetivo\b/gi, 'goal'],
  [/\bmetas\b/gi, 'goals'],
  [/\bmeta\b/gi, 'goal'],
  [/\brecompensas\b/gi, 'rewards'],
  [/\brecompensa\b/gi, 'reward'],
  [/\bprogresso\b/gi, 'progress'],
  [/\bevolução\b/gi, 'progression'],
  [/\brecuperação\b/gi, 'recovery'],
  [/\bnutrição\b/gi, 'nutrition'],
  [/\bdescanso\b/gi, 'rest'],
  [/\bfinanças\b/gi, 'finances'],
  [/\bpróximo nível\b/gi, 'next level'],
  [/\bnível\b/gi, 'level'],
  [/\bpróxima\b/gi, 'next'],
  [/\bpróximo\b/gi, 'next'],
  [/\bdiárias\b/gi, 'daily'],
  [/\bdiários\b/gi, 'daily'],
  [/\bdiária\b/gi, 'daily'],
  [/\bdiário\b/gi, 'daily'],
  [/\bconcluídas\b/gi, 'completed'],
  [/\bconcluídos\b/gi, 'completed'],
  [/\bconcluída\b/gi, 'completed'],
  [/\bconcluído\b/gi, 'completed'],
  [/\bpendentes\b/gi, 'pending'],
  [/\bpendente\b/gi, 'pending'],
  [/\bdias\b/gi, 'days'],
  [/\bdia\b/gi, 'day'],
  [/\bganhos\b/gi, 'earned'],
  [/\bganho\b/gi, 'earned'],
  [/\brestantes\b/gi, 'remaining'],
  [/\brestante\b/gi, 'remaining'],
  [/\bregistrado\b/gi, 'recorded'],
  [/\bregistrada\b/gi, 'recorded'],
  [/\bselecionado\b/gi, 'selected'],
  [/\bselecionada\b/gi, 'selected'],
  [/\bexcluir\b/gi, 'delete'],
  [/\bsalvar\b/gi, 'save'],
  [/\bcancelar\b/gi, 'cancel'],
  [/\bconfirmar\b/gi, 'confirm'],
  [/\badicionar\b/gi, 'add'],
  [/\beditar\b/gi, 'edit'],
  [/\bfechar\b/gi, 'close'],
  [/\bvoltar\b/gi, 'back'],
  [/\bcontinuar\b/gi, 'continue'],
  [/\bcarregando\b/gi, 'loading'],
  [/\bsincronizando\b/gi, 'synchronizing'],
];

export function translateUiText(value: string) {
  const leading = value.match(/^\s*/)?.[0] ?? '';
  const trailing = value.match(/\s*$/)?.[0] ?? '';
  const text = value.trim();
  if (!text) return value;

  let translated = EXACT_ENGLISH[text] ?? text;
  if (translated === text) {
    for (const [pattern, replacement] of REPLACEMENTS) {
      translated = translated.replace(pattern, replacement);
    }
  }
  return `${leading}${translated}${trailing}`;
}
